import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { UserCommonService } from './user-common.service';

/**
 * Service responsible for user generated ideas operations.
 *
 * This service handles retrieving ideas generated
 * by the authenticated user.
 *
 * It uses UserCommonService for shared user validation logic.
 *
 * @author Eman
 */
@Injectable()
export class UserIdeasService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly userCommonService: UserCommonService,
  ) { }

  /**
   * Retrieves the authenticated user's generated ideas.
   *
   * Returns all ideas generated by the authenticated user,
   * ordered from newest to oldest.
   *
   * @param userId - Authenticated user ID.
   * @returns List of generated ideas.
   *
   * @throws NotFoundException if the user does not exist.
   */
  async getGeneratedIdeas(userId: string) {
    await this.userCommonService.findUserOrThrow(userId);

    return this.prisma.idea.findMany({
      where: { userId },
      orderBy: {
        createdAt: 'desc',
      },
      select: {
        id: true,
        title: true,
        partialAbstract: true,
        fullAbstract: true,
        generationType: true,
        isUnlocked: true,
        unlockMethod: true,
        commentsCount: true,
        selectedRegion: true,
        createdAt: true,
        domain: true,
        selectedPlatform: true,
      },
    });
  }
}