import { useEffect, useState } from 'react';
import { RefreshCw, Save, Sparkles } from 'lucide-react';
import { adminApi, getApiErrorMessage } from '../api/adminApi';
import '../styles/admin-pages.css';

export default function AdminPromptsPage(){
 const [template,setTemplate]=useState(null);const [history,setHistory]=useState([]);const [text,setText]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError('');try{const [tpl,h]=await Promise.all([adminApi.prompts.template(),adminApi.prompts.history({page:1,limit:12})]);setTemplate(tpl);setText(tpl?.ideaPromptTemplate||tpl?.template||tpl?.content||tpl?.prompt||'');setHistory(Array.isArray(h)?h:(h?.items||h?.history||h?.records||[]));}catch(e){setError(getApiErrorMessage(e,'Could not load prompt configuration.'));}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const save=async()=>{setBusy(true);setError('');try{await adminApi.prompts.update({ ideaPromptTemplate: text });await load();}catch(e){setError(getApiErrorMessage(e,'Could not update prompt template.'));}finally{setBusy(false);}};
 return <div className="admin-page"><section className="admin-hero"><div className="admin-hero__eyebrow"><Sparkles size={14}/> Generation governance</div><h2>Prompt control</h2><p>Edit the active prompt template and inspect its history. This interface uses the existing protected prompt template and history endpoints.</p></section>{error&&<div className="admin-error">{error}</div>}<section className="admin-dashboard-grid"><article className="admin-panel"><header className="admin-panel__head"><div><h3>Active template</h3><p>Production prompt configuration</p></div><div className="admin-toolbar"><button className="admin-btn" onClick={load}><RefreshCw size={13}/> Reload</button><button className="admin-btn admin-btn--primary" onClick={save} disabled={busy}><Save size={13}/> Save</button></div></header>{loading?<div className="admin-loading"><div className="admin-spinner"/></div>:<div className="admin-modal__body"><div className="admin-field"><label>Prompt template</label><textarea style={{minHeight:420,fontFamily:'ui-monospace, SFMono-Regular, Menlo, monospace',lineHeight:1.55}} value={text} onChange={e=>setText(e.target.value)}/></div></div>}</article><article className="admin-panel"><header className="admin-panel__head"><div><h3>Template history</h3><p>Recent revisions</p></div></header><div className="admin-activity">{history.length?history.map((item,i)=><div className="admin-activity__item" key={item.id||i}><span className="admin-activity__dot"><Sparkles size={14}/></span><div><strong>{item.name||item.version||`Revision ${i+1}`}</strong><span>{item.updatedBy?.fullName||item.user?.fullName||'Administrator'} · {item.createdAt?new Date(item.createdAt).toLocaleString():'Saved revision'}</span></div></div>):<div className="admin-empty"><p>No prompt history returned.</p></div>}</div></article></section></div>;
}