/**
 * Shared provider-neutral JSON Schema field definitions used by idea
 * generation and idea-unlock output contracts.
 *
 * These definitions centralize repeated validation constraints so that
 * guest, free, premium, and unlock schemas remain consistent.
 *
 * Final output schemas remain responsible for:
 * - Selecting the fields required by their workflow.
 * - Defining the required property list.
 * - Rejecting unknown properties.
 *
 * @author Malak
 */

/**
 * Shared generated software-project title schema.
 */
export const IDEA_TITLE_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 3,
  maxLength: 200,
} as const;

/**
 * Problem-statement schema used by guest and registered free idea
 * generation.
 */
export const FREE_PROBLEM_STATEMENT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 20,
  maxLength: 1_200,
} as const;

/**
 * Problem-statement schema used by premium idea generation.
 *
 * Premium generation allows a longer description because it returns a
 * complete project-planning result.
 */
export const PREMIUM_PROBLEM_STATEMENT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 20,
  maxLength: 1_500,
} as const;

/**
 * Shared project-objectives schema.
 */
export const IDEA_OBJECTIVES_OUTPUT_PROPERTY = {
  type: 'array',
  minItems: 1,
  maxItems: 10,
  items: {
    type: 'string',
    minLength: 3,
    maxLength: 300,
  },
} as const;

/**
 * Shared target-users schema.
 */
export const IDEA_TARGET_USERS_OUTPUT_PROPERTY = {
  type: 'array',
  minItems: 1,
  maxItems: 10,
  items: {
    type: 'string',
    minLength: 2,
    maxLength: 200,
  },
} as const;

/**
 * Partial project abstract schema used by guest and registered free
 * generation.
 */
export const PARTIAL_ABSTRACT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 30,
  maxLength: 2_500,
} as const;

/**
 * Limited project abstract exposed to unauthenticated guests.
 */
export const LIMITED_ABSTRACT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 20,
  maxLength: 1_200,
} as const;

/**
 * Complete project abstract schema used by premium generation and idea
 * unlocking.
 */
export const FULL_ABSTRACT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 50,
  maxLength: 5_000,
} as const;

/**
 * Shared advanced idea fields generated by:
 * - Premium credit-based idea generation.
 * - Direct unlocking of an existing free idea.
 *
 * Trusted source data from NlpAnalysis is intentionally excluded.
 */
export const ADVANCED_IDEA_OUTPUT_PROPERTIES = {
  /**
   * Recommended implementation technologies.
   */
  technologyStack: {
    type: 'array',
    minItems: 1,
    maxItems: 12,
    items: {
      type: 'string',
      minLength: 1,
      maxLength: 100,
    },
  },

  /**
   * High-level system architecture recommendation.
   */
  systemArchitecture: {
    type: 'string',
    minLength: 20,
    maxLength: 4_000,
  },

  /**
   * Preliminary database-design recommendation.
   */
  databaseDesign: {
    type: 'string',
    minLength: 20,
    maxLength: 4_000,
  },

  /**
   * Minimum viable product features.
   */
  mvpFeatures: {
    type: 'array',
    minItems: 3,
    maxItems: 15,
    items: {
      type: 'string',
      minLength: 3,
      maxLength: 300,
    },
  },

  /**
   * Preliminary business-model recommendation.
   */
  businessModel: {
    type: 'string',
    minLength: 20,
    maxLength: 2_500,
  },

  /**
   * Suggested revenue streams and monetization strategy.
   */
  revenueModel: {
    type: 'string',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Preliminary project budget range and assumptions.
   */
  budgetEstimation: {
    type: 'string',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Suggested project implementation timeline.
   */
  implementationTimeline: {
    type: 'string',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Technical and operational feasibility assessment.
   */
  feasibilityAssessment: {
    type: 'string',
    minLength: 20,
    maxLength: 2_500,
  },

  /**
   * Preliminary assessment of market opportunity.
   */
  marketPotential: {
    type: 'string',
    minLength: 20,
    maxLength: 2_500,
  },

  /**
   * High-level local regulatory considerations.
   *
   * This value must not be presented as verified legal advice.
   */
  localRegulations: {
    type: 'string',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Explanation of the value offered to target users.
   */
  valueProposition: {
    type: 'string',
    minLength: 20,
    maxLength: 1_800,
  },

  /**
   * AI-generated readable interpretation of trusted NLP data.
   */
  nlpExecutiveSummary: {
    type: 'string',
    minLength: 20,
    maxLength: 2_500,
  },

  /**
   * AI-generated readable summary of community feedback.
   */
  communityFeedbackSummary: {
    type: 'string',
    minLength: 20,
    maxLength: 1_500,
  },
} as const;

/**
 * Required advanced field names shared by premium generation and idea
 * unlocking.
 */
export const ADVANCED_IDEA_REQUIRED_FIELDS = [
  'technologyStack',
  'systemArchitecture',
  'databaseDesign',
  'mvpFeatures',
  'businessModel',
  'revenueModel',
  'budgetEstimation',
  'implementationTimeline',
  'feasibilityAssessment',
  'marketPotential',
  'localRegulations',
  'valueProposition',
  'nlpExecutiveSummary',
  'communityFeedbackSummary',
] as const;

/**
 * Shared human-readable output example fields for the common idea
 * foundation.
 */
export const BASE_IDEA_OUTPUT_FORMAT = {
  title: 'string',
  problemStatement: 'string',
  objectives: ['string'],
  targetUsers: ['string'],
} as const;

/**
 * Shared human-readable output example fields for advanced idea
 * generation.
 */
export const ADVANCED_IDEA_OUTPUT_FORMAT = {
  technologyStack: ['string'],
  systemArchitecture: 'string',
  databaseDesign: 'string',
  mvpFeatures: ['string'],
  businessModel: 'string',
  revenueModel: 'string',
  budgetEstimation: 'string',
  implementationTimeline: 'string',
  feasibilityAssessment: 'string',
  marketPotential: 'string',
  localRegulations: 'string',
  valueProposition: 'string',
  nlpExecutiveSummary: 'string',
  communityFeedbackSummary: 'string',
} as const;