/**
 * Shared provider-neutral JSON Schema field definitions used by idea
 * generation and idea-unlock output contracts.
 *
 * These definitions centralize repeated validation constraints so that
 * guest, free, premium, and unlock schemas remain consistent.
 *
 * Final output schemas remain responsible for:
 * - Selecting the fields required by their workflow.
 * - Defining the required property list.
 * - Rejecting unknown properties.
 *
 * @author Malak
 */

/**
 * Shared generated software-project title schema.
 */
export const IDEA_TITLE_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 3,
  maxLength: 200,
} as const;

/**
 * Multi-problem portfolio schema used by guest and registered free idea
 * generation. The string remains backward compatible with the current database
 * while containing numbered problem-to-solution entries.
 */
export const FREE_PROBLEM_STATEMENT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 20,
  maxLength: 3_000,
} as const;

/**
 * Problem-statement schema used by premium idea generation.
 *
 * Premium uses the same maximum so cross-domain problem-to-solution entries
 * remain consistent across account tiers.
 */
export const PREMIUM_PROBLEM_STATEMENT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 20,
  maxLength: 3_000,
} as const;

/**
 * Shared project-objectives schema.
 */
export const IDEA_OBJECTIVES_OUTPUT_PROPERTY = {
  type: 'array',
  minItems: 1,
  maxItems: 10,
  items: {
    type: 'string',
    minLength: 3,
    maxLength: 300,
  },
} as const;

/**
 * Shared target-users schema.
 */
export const IDEA_TARGET_USERS_OUTPUT_PROPERTY = {
  type: 'array',
  minItems: 1,
  maxItems: 10,
  items: {
    type: 'string',
    minLength: 2,
    maxLength: 200,
  },
} as const;

/**
 * Partial project abstract schema used by guest and registered free
 * generation.
 */
export const PARTIAL_ABSTRACT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 30,
  maxLength: 2_500,
} as const;

/**
 * Limited project abstract exposed to unauthenticated guests.
 */
export const LIMITED_ABSTRACT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 20,
  maxLength: 1_200,
} as const;

/**
 * Complete project abstract schema used by premium generation and idea
 * unlocking.
 */
export const FULL_ABSTRACT_OUTPUT_PROPERTY = {
  type: 'string',
  minLength: 50,
  maxLength: 5_000,
} as const;

/**
 * Shared advanced idea fields generated by:
 * - Premium credit-based idea generation.
 * - Direct unlocking of an existing free idea.
 *
 * Trusted source data from NlpAnalysis is intentionally excluded.
 */
export const ADVANCED_IDEA_OUTPUT_PROPERTIES = {
  /**
   * Recommended implementation technologies.
   */
  technologyStack: {
    type: 'array',
    description:
      'Return only concrete technology, framework, database, infrastructure, and tooling names as a stable list. Do not mix architecture narrative or evidence qualifiers into this array.',
    minItems: 1,
    maxItems: 12,
    items: {
      type: 'string',
      minLength: 1,
      maxLength: 100,
    },
  },

  /**
   * High-level system architecture recommendation.
   */
  systemArchitecture: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Architecture Style, Request Flow, Application Services, Data Persistence, Background Processing, Access & Security, Integrations. Format every section as "Label: content." Do not rename or reorder labels. If a section is not applicable, state that briefly instead of omitting it.',
    minLength: 20,
    maxLength: 4_000,
  },

  /**
   * Preliminary database-design recommendation.
   */
  databaseDesign: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Schema Foundation, Core Entities, Relationships, Indexes & Lookup. Format every section as "Label: content." Do not rename or reorder labels.',
    minLength: 20,
    maxLength: 4_000,
  },

  /**
   * Minimum viable product features.
   */
  mvpFeatures: {
    type: 'array',
    description:
      'Return one concrete MVP capability per array item. Every item must use the same concise feature style: capability first, then the user or operational outcome. Do not add headings, numbering, or duplicate features.',
    minItems: 3,
    maxItems: 15,
    items: {
      type: 'string',
      minLength: 3,
      maxLength: 300,
    },
  },

  /**
   * Suggested revenue streams and monetization strategy.
   */
  revenueModel: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Primary Revenue, Secondary Revenue, Pricing Logic, Buyer. Format every section as "Label: content." Do not invent a revenue stream that the proposed product could not plausibly support.',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Preliminary project budget range and assumptions.
   */
  budgetEstimation: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Budget Range, Cost Structure, Assumptions, Excluded Costs. Format every section as "Label: content." Any numeric amount must be clearly framed as a preliminary estimate or planning assumption, never an observed fact.',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Suggested project implementation timeline.
   */
  implementationTimeline: {
    type: 'string',
    description:
      'Use exactly four implementation phases in this exact order: Phase 1, Phase 2, Phase 3, Phase 4. Format each as "Phase N: content." Include timing or duration inside the content when useful, and keep the phases sequential from planning through validation or rollout.',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Technical and operational feasibility assessment.
   */
  feasibilityAssessment: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Technical Feasibility, Operational Feasibility, Economic Feasibility, Regulatory Feasibility, Delivery Feasibility. Format every section as "Label: content." Preserve uncertainty where evidence is limited.',
    minLength: 20,
    maxLength: 2_500,
  },

  /**
   * Preliminary assessment of market opportunity.
   */
  marketPotential: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Demand Status, Evidence Coverage, Direct-user Validation, Next Validation Step. Format every section as "Label: content." Never convert secondary evidence into verified market-wide demand.',
    minLength: 20,
    maxLength: 2_500,
  },

  /**
   * High-level local regulatory considerations.
   *
   * This value must not be presented as verified legal advice.
   */
  localRegulations: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Data Protection & Privacy, Record-Keeping, Domain Regulations, Deployment Review. Format every section as "Label: content." Keep all regulatory statements preliminary and recommend local verification where appropriate.',
    minLength: 20,
    maxLength: 2_000,
  },

  /**
   * Explanation of the value offered to target users.
   */
  valueProposition: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Primary Value, User Outcome, Differentiation. Format every section as "Label: content." Keep the value tied to the evidence-backed workflow.',
    minLength: 20,
    maxLength: 1_800,
  },

  /**
   * AI-generated readable interpretation of trusted NLP data.
   */
  nlpExecutiveSummary: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Processing Coverage, Evidence Retained, Language Synthesis, Excluded Corpus. Format every section as "Label: content." Use only trusted NLP values supplied in context and do not fabricate counts.',
    minLength: 20,
    maxLength: 2_500,
  },

  /**
   * AI-generated readable summary of community feedback.
   */
  communityFeedbackSummary: {
    type: 'string',
    description:
      'Use these exact labeled sections in this exact order, each as one complete sentence: Retained Evidence, Scope Interpretation, Community Signal, Excluded Findings. Format every section as "Label: content." Distinguish supporting evidence from context-only or unrelated material.',
    minLength: 20,
    maxLength: 1_500,
  },
} as const;

/**
 * Required advanced field names shared by premium generation and idea
 * unlocking.
 */
export const ADVANCED_IDEA_REQUIRED_FIELDS = [
  'technologyStack',
  'systemArchitecture',
  'databaseDesign',
  'mvpFeatures',
  'revenueModel',
  'budgetEstimation',
  'implementationTimeline',
  'feasibilityAssessment',
  'marketPotential',
  'localRegulations',
  'valueProposition',
  'nlpExecutiveSummary',
  'communityFeedbackSummary',
] as const;

/**
 * Shared human-readable output example fields for the common idea
 * foundation.
 */
export const BASE_IDEA_OUTPUT_FORMAT = {
  title: 'string',
  problemStatement: 'string',
  objectives: ['string'],
  targetUsers: ['string'],
} as const;

/**
 * Shared human-readable output example fields for advanced idea
 * generation.
 */
export const ADVANCED_IDEA_OUTPUT_FORMAT = {
  technologyStack: ['technology name'],
  systemArchitecture:
    'Architecture Style: ... . Request Flow: ... . Application Services: ... . Data Persistence: ... . Background Processing: ... . Access & Security: ... . Integrations: ... .',
  databaseDesign:
    'Schema Foundation: ... . Core Entities: ... . Relationships: ... . Indexes & Lookup: ... .',
  mvpFeatures: ['one concrete MVP capability per item'],
  revenueModel:
    'Primary Revenue: ... . Secondary Revenue: ... . Pricing Logic: ... . Buyer: ... .',
  budgetEstimation:
    'Budget Range: ... . Cost Structure: ... . Assumptions: ... . Excluded Costs: ... .',
  implementationTimeline:
    'Phase 1: ... . Phase 2: ... . Phase 3: ... . Phase 4: ... .',
  feasibilityAssessment:
    'Technical Feasibility: ... . Operational Feasibility: ... . Economic Feasibility: ... . Regulatory Feasibility: ... . Delivery Feasibility: ... .',
  marketPotential:
    'Demand Status: ... . Evidence Coverage: ... . Direct-user Validation: ... . Next Validation Step: ... .',
  localRegulations:
    'Data Protection & Privacy: ... . Record-Keeping: ... . Domain Regulations: ... . Deployment Review: ... .',
  valueProposition:
    'Primary Value: ... . User Outcome: ... . Differentiation: ... .',
  nlpExecutiveSummary:
    'Processing Coverage: ... . Evidence Retained: ... . Language Synthesis: ... . Excluded Corpus: ... .',
  communityFeedbackSummary:
    'Retained Evidence: ... . Scope Interpretation: ... . Community Signal: ... . Excluded Findings: ... .',
} as const;