/**
 * Provider-neutral JSON schema describing the expected response
 * for premium credit-based idea generation.
 *
 * The AI generates:
 * - Complete project-planning content.
 * - A readable executive summary of the persisted NLP analysis.
 * - A readable summary of the collected community feedback.
 *
 * Trusted NLP data such as:
 * - recurring problems
 * - extracted keywords
 * - sample comments
 * - analyzed comments count
 * - NLP confidence
 *
 * must not be generated by AI. Those values are appended later
 * from NlpAnalysis by IdeasService or a dedicated response builder.
 *
 * AI provider adapters may transform this schema into:
 * - OpenAI Structured Outputs.
 * - Gemini responseSchema.
 * - Anthropic tool-input schema.
 *
 * @author Malak
 */
export const PREMIUM_OUTPUT_SCHEMA = {
  type: 'object',
  additionalProperties: false,

  properties: {
    /**
     * Generated software project title.
     */
    title: {
      type: 'string',
      minLength: 1,
      maxLength: 200,
    },

    /**
     * Description of the real problem addressed by the project.
     */
    problemStatement: {
      type: 'string',
      minLength: 1,
      maxLength: 1500,
    },

    /**
     * Main project goals and expected outcomes.
     */
    objectives: {
      type: 'string',
      minLength: 1,
      maxLength: 1500,
    },

    /**
     * Primary users or organizations expected to use the project.
     */
    targetUsers: {
      type: 'string',
      minLength: 1,
      maxLength: 1000,
    },

    /**
     * Complete project abstract.
     */
    fullAbstract: {
      type: 'string',
      minLength: 1,
      maxLength: 5000,
    },

    /**
     * Recommended technologies required to implement the project.
     */
    technologyStack: {
      type: 'array',
      minItems: 1,
      maxItems: 12,
      items: {
        type: 'string',
        minLength: 1,
        maxLength: 100,
      },
    },

    /**
     * High-level system architecture recommendation.
     */
    systemArchitecture: {
      type: 'string',
      minLength: 1,
      maxLength: 4000,
    },

    /**
     * Preliminary database-design recommendation.
     */
    databaseDesign: {
      type: 'string',
      minLength: 1,
      maxLength: 4000,
    },

    /**
     * Minimum viable product features.
     */
    mvpFeatures: {
      type: 'array',
      minItems: 3,
      maxItems: 15,
      items: {
        type: 'string',
        minLength: 1,
        maxLength: 300,
      },
    },

    /**
     * Preliminary business-model recommendation.
     */
    businessModel: {
      type: 'string',
      minLength: 1,
      maxLength: 2500,
    },

    /**
     * Suggested revenue streams and monetization strategy.
     */
    revenueModel: {
      type: 'string',
      minLength: 1,
      maxLength: 2000,
    },

    /**
     * Preliminary project budget range.
     */
    budgetEstimation: {
      type: 'string',
      minLength: 1,
      maxLength: 2000,
    },

    /**
     * Suggested project implementation timeline.
     */
    implementationTimeline: {
      type: 'string',
      minLength: 1,
      maxLength: 2000,
    },

    /**
     * Technical and operational feasibility assessment.
     */
    feasibilityAssessment: {
      type: 'string',
      minLength: 1,
      maxLength: 2500,
    },

    /**
     * Preliminary assessment of the project's market opportunity.
     */
    marketPotential: {
      type: 'string',
      minLength: 1,
      maxLength: 2500,
    },

    /**
     * High-level local regulatory considerations.
     *
     * This field must not be presented as verified legal advice.
     */
    localRegulations: {
      type: 'string',
      minLength: 1,
      maxLength: 2000,
    },

    /**
     * Explanation of the unique value offered to target users.
     */
    valueProposition: {
      type: 'string',
      minLength: 1,
      maxLength: 1800,
    },

    /**
     * AI-generated readable interpretation of the trusted NLP data.
     *
     * This is not the raw NlpAnalysis database record.
     */
    nlpExecutiveSummary: {
      type: 'string',
      minLength: 1,
      maxLength: 2500,
    },

    /**
     * AI-generated readable summary of the supplied posts,
     * comments, recurring problems, and community needs.
     *
     * This is not a replacement for the trusted comments,
     * sample evidence, or NLP values stored in the database.
     */
    communityFeedbackSummary: {
      type: 'string',
      minLength: 1,
      maxLength: 1500,
    },
  },

  required: [
    'title',
    'problemStatement',
    'objectives',
    'targetUsers',
    'fullAbstract',
    'technologyStack',
    'systemArchitecture',
    'databaseDesign',
    'mvpFeatures',
    'businessModel',
    'revenueModel',
    'budgetEstimation',
    'implementationTimeline',
    'feasibilityAssessment',
    'marketPotential',
    'localRegulations',
    'valueProposition',
    'nlpExecutiveSummary',
    'communityFeedbackSummary',
  ],
} as const;

/**
 * Human-readable JSON example inserted into the prompt.
 *
 * The AI must follow these exact field names and value types.
 * Trusted NLP and collection metadata are appended later
 * by the application and are not included in this format.
 */
export const PREMIUM_OUTPUT_FORMAT = JSON.stringify(
  {
    title: 'string',
    problemStatement: 'string',
    objectives: 'string',
    targetUsers: 'string',
    fullAbstract: 'string',
    technologyStack: ['string'],
    systemArchitecture: 'string',
    databaseDesign: 'string',
    mvpFeatures: ['string'],
    businessModel: 'string',
    revenueModel: 'string',
    budgetEstimation: 'string',
    implementationTimeline: 'string',
    feasibilityAssessment: 'string',
    marketPotential: 'string',
    localRegulations: 'string',
    valueProposition: 'string',
    nlpExecutiveSummary: 'string',
    communityFeedbackSummary: 'string',
  },
  null,
  2,
);
