import {
  IntelligentAnalysisOutput,
  TextAnalysisResult,
} from '../../pipeline/types/intelligent-analysis.types';

/**
 * Represents the rule-based NLP data required to calculate
 * analysis quality metrics.
 *
 * This input reuses the existing Nexora AI analysis contracts
 * instead of receiving duplicated counters from the caller.
 *
 * This approach reduces the risk of inconsistent values and keeps
 * metric calculations aligned with the actual NLP output.
 *
 * The final confidence and AI usage state are intentionally excluded
 * because they are calculated or updated after quality evaluation.
 *
 * @author Eman
 */
export type AnalysisMetricsInput = {
  /**
   * Total number of relevant texts retained and analyzed after
   * cleaning, duplicate removal, spam filtering, and relevance filtering.
   */
  readonly totalTextsAnalyzed: number;

  /**
   * Summary of texts removed during preprocessing.
   *
   * These values are used to reconstruct the original collected
   * dataset size and calculate the data-retention rate.
   */
  readonly dataQuality: IntelligentAnalysisOutput['dataQuality'];

  /**
   * Keywords extracted by the rule-based NLP pipeline.
   */
  readonly keywords: IntelligentAnalysisOutput['keywords'];

  /**
   * Topics inferred from recurring community discussion signals.
   */
  readonly topics: IntelligentAnalysisOutput['topics'];

  /**
   * Recurring problems detected in analyzed posts and comments.
   */
  readonly recurringProblems: IntelligentAnalysisOutput['recurringProblems'];

  /**
   * User needs and unmet requirements extracted from community feedback.
   */
  readonly extractedNeeds: IntelligentAnalysisOutput['extractedNeeds'];

  /**
   * Feature requests discovered in analyzed discussions.
   */
  readonly featureRequests: IntelligentAnalysisOutput['featureRequests'];

  /**
   * Evidence-based opportunity signals generated by the rule-based analysis.
   */
  readonly opportunities: IntelligentAnalysisOutput['opportunities'];

  /**
   * Detailed result for every analyzed text.
   *
   * Used to calculate:
   * - Average text confidence.
   * - Lexical coverage.
   * - Text-level quality consistency.
   */
  readonly analyzedTexts: readonly TextAnalysisResult[];
};
