import { z } from 'zod';

/**
 * Reusable Zod validators shared by idea-generation schemas.
 *
 * Centralizing these validators prevents validation rules from
 * diverging between guest, free, premium, and unlock workflows.
 *
 * These schemas validate individual fields only. Final output schemas
 * remain responsible for defining which fields are required for each
 * generation type and for rejecting unknown properties.
 *
 * @author Malak
 */
export const IdeaSharedFields = {
  /**
   * Generated software-project title.
   */
  title: z.string().trim().min(3).max(200),

  /**
   * Description of the real problem addressed by the project.
   */
  problemStatement: z.string().trim().min(20).max(1_500),

  /**
   * Main project goals and expected outcomes.
   */
  objectives: z.array(z.string().trim().min(3).max(300)).min(1).max(10),

  /**
   * Primary users or organizations expected to use the project.
   */
  targetUsers: z.array(z.string().trim().min(2).max(200)).min(1).max(10),

  /**
   * Partial project abstract available to authenticated free users.
   */
  partialAbstract: z.string().trim().min(30).max(2_500),

  /**
   * Limited project abstract exposed to unauthenticated guests.
   */
  limitedAbstract: z.string().trim().min(20).max(1_200),

  /**
   * Complete project abstract.
   */
  fullAbstract: z.string().trim().min(50).max(5_000),
} satisfies z.ZodRawShape;

/**
 * Reusable Zod validators shared by premium generation and idea
 * unlocking.
 *
 * Trusted NLP facts such as recurring problems, extracted keywords,
 * confidence values, sample comments, and analyzed-comment counts are
 * intentionally excluded.
 *
 * Those values must be loaded directly from the persisted NlpAnalysis
 * record instead of being regenerated by the AI provider.
 *
 * @author Malak
 */
export const AdvancedIdeaFields = {
  /**
   * Recommended technologies, frameworks, databases, infrastructure,
   * and supporting tools.
   */
  technologyStack: z.array(z.string().trim().min(1).max(100)).min(1).max(12),

  /**
   * High-level system architecture recommendation.
   */
  systemArchitecture: z.string().trim().min(20).max(4_000),

  /**
   * Preliminary database-design recommendation.
   */
  databaseDesign: z.string().trim().min(20).max(4_000),

  /**
   * Minimum viable product features.
   */
  mvpFeatures: z.array(z.string().trim().min(3).max(300)).min(3).max(15),

  /**
   * Preliminary business-model recommendation.
   */
  businessModel: z.string().trim().min(20).max(2_500),

  /**
   * Suggested revenue streams and monetization strategy.
   */
  revenueModel: z.string().trim().min(20).max(2_000),

  /**
   * Preliminary budget range and the assumptions used to estimate it.
   */
  budgetEstimation: z.string().trim().min(20).max(2_000),

  /**
   * Suggested implementation phases and timeline.
   */
  implementationTimeline: z.string().trim().min(20).max(2_000),

  /**
   * Technical and operational feasibility assessment.
   */
  feasibilityAssessment: z.string().trim().min(20).max(2_500),

  /**
   * Preliminary assessment of the project's market opportunity.
   */
  marketPotential: z.string().trim().min(20).max(2_500),

  /**
   * High-level local regulatory considerations.
   *
   * This value must not be presented as verified legal advice.
   */
  localRegulations: z.string().trim().min(20).max(2_000),

  /**
   * Explanation of the value delivered to the target users.
   */
  valueProposition: z.string().trim().min(20).max(1_800),

  /**
   * AI-generated readable interpretation of trusted persisted NLP data.
   *
   * This field is a narrative summary and must not replace the raw
   * NlpAnalysis record.
   */
  nlpExecutiveSummary: z.string().trim().min(20).max(2_500),

  /**
   * AI-generated readable summary of the supplied community feedback.
   */
  communityFeedbackSummary: z.string().trim().min(20).max(1_500),
} satisfies z.ZodRawShape;
