import { AiEnhancementOutput } from './ai-enhancement-output.type';

/**
 * Types describing the contract between the NLP AI-enhancement
 * layer and its AI client implementation.
 *
 * These contracts remain independent from the central AI execution
 * module and define only the information required by the NLP layer.
 *
 * @author Eman
 */

/**
 * Request sent by the NLP enhancement layer to an AI client.
 */
export type NlpAiClientRequest = {
  /**
   * Fully rendered prompt sent to the AI model.
   */
  readonly prompt: string;

  /**
   * Optional logical operation identifier used for tracing
   * and correlation across logs.
   */
  readonly operationId?: string;
};

/**
 * Normalized response returned by an AI client implementation.
 */
export type NlpAiClientResponse = {
  /**
   * Parsed and validated AI enhancement output.
   */
  readonly data: AiEnhancementOutput;

  /**
   * AI provider that generated the response.
   *
   * Example:
   * - OPENAI
   * - ANTHROPIC
   * - GOOGLE
   */
  readonly provider?: string;

  /**
   * External AI model identifier.
   *
   * Example:
   * - gpt-5
   * - claude-sonnet-4
   * - gemini-2.5-pro
   */
  readonly modelId?: string;

  /**
   * Number of input tokens consumed by the request.
   */
  readonly inputTokens?: number;

  /**
   * Number of output tokens generated by the model.
   */
  readonly outputTokens?: number;

  /**
   * Total provider response time in milliseconds.
   */
  readonly responseTimeMs?: number;

  /**
   * Estimated execution cost.
   */
  readonly estimatedCost?: number;
};
