import { LanguageCode } from '@prisma/client';

/**
 * Stop words dictionary used by the NLP pipeline.
 *
 * Stop words are common words that usually do not carry strong semantic
 * meaning during keyword extraction, topic detection, and recurring problem
 * analysis. Removing them helps the system focus on meaningful terms found
 * in community posts and comments.
 *
 * In Nexora AI, this dictionary supports multilingual data collection and NLP
 * analysis across the currently supported languages. The `ANY` language option
 * is intentionally kept empty because it represents an unknown or mixed-language
 * input where language-specific filtering should not be forced.
 *
 * Usage examples:
 * - Cleaning collected social posts before keyword extraction.
 * - Reducing noise in recurring problem detection.
 * - Improving generated prompt context quality before sending data to the AI.
 *
 * Notes:
 * - Keys must stay synchronized with the `LanguageCode` enum in Prisma.
 * - Add new language entries here whenever a new language is added to Prisma.
 * - Keep words lowercase to match normalized text processing.
 *
 * @author Eman
 */
export const STOP_WORDS: Record<LanguageCode, string[]> = {
  [LanguageCode.EN]: [
    'a',
    'an',
    'and',
    'are',
    'as',
    'at',
    'be',
    'been',
    'being',
    'but',
    'by',
    'for',
    'from',
    'had',
    'has',
    'have',
    'he',
    'her',
    'here',
    'hers',
    'herself',
    'him',
    'himself',
    'his',
    'how',
    'i',
    'if',
    'in',
    'into',
    'is',
    'it',
    'its',
    'itself',
    'me',
    'more',
    'most',
    'my',
    'myself',
    'no',
    'nor',
    'not',
    'of',
    'on',
    'once',
    'only',
    'or',
    'other',
    'our',
    'ours',
    'ourselves',
    'out',
    'over',
    'she',
    'should',
    'so',
    'some',
    'such',
    'than',
    'that',
    'the',
    'their',
    'theirs',
    'them',
    'themselves',
    'then',
    'there',
    'these',
    'they',
    'this',
    'those',
    'through',
    'to',
    'too',
    'under',
    'until',
    'up',
    'very',
    'was',
    'we',
    'were',
    'what',
    'when',
    'where',
    'which',
    'while',
    'who',
    'whom',
    'why',
    'will',
    'with',
    'would',
    'you',
    'your',
    'yours',
    'yourself',
    'yourselves',
    'all',
    'any',
    'anything',
    'can',
    'could',
    'every',
    'get',
    'got',
    'just',
    'like',
    'may',
    'might',
    'need',
    'needs',
    'one',
    'problem',
    'problems',
    'really',
    'thing',
    'things',
    'time',
    'use',
    'used',
    'using',
    'want',
    'without',
    'work',
    'works',
  ],

  [LanguageCode.AR]: [
    'و',
    'أو',
    'في',
    'من',
    'على',
    'إلى',
    'عن',
    'مع',
    'هذا',
    'هذه',
    'ذلك',
    'تلك',
    'الذي',
    'التي',
    'الذين',
    'كان',
    'كانت',
    'يكون',
    'تكون',
    'قد',
    'لقد',
    'لن',
    'لم',
    'لا',
    'ما',
    'ماذا',
    'متى',
    'كيف',
    'أين',
    'هناك',
    'هنا',
    'كل',
    'بعض',
    'جميع',
    'أي',
    'أيضا',
    'أيضًا',
    'بين',
    'بعد',
    'قبل',
    'حتى',
    'إن',
    'أن',
    'أنه',
    'أنها',
    'هو',
    'هي',
    'هم',
    'هن',
    'أنا',
    'نحن',
    'أنت',
    'أنتم',
    'أنتن',
  ],

  [LanguageCode.FR]: [
    'le',
    'la',
    'les',
    'de',
    'des',
    'du',
    'et',
    'à',
    'en',
    'pour',
  ],

  [LanguageCode.ES]: [
    'el',
    'la',
    'los',
    'las',
    'de',
    'del',
    'y',
    'en',
    'para',
    'con',
  ],

  [LanguageCode.DE]: [
    'der',
    'die',
    'das',
    'und',
    'ist',
    'zu',
    'mit',
    'von',
    'für',
    'ein',
  ],

  [LanguageCode.TR]: [
    've',
    'bir',
    'bu',
    'şu',
    'ile',
    'için',
    'da',
    'de',
    'çok',
    'olan',
  ],

  [LanguageCode.ANY]: [],
};