import {
  Controller,
  Delete,
  Get,
  Param,
  ParseUUIDPipe,
  Post,
  UseGuards,
} from '@nestjs/common';

import { CurrentUser } from '../../auth/decorators/current-user.decorator';
import { JwtAuthGuard } from '../../auth/guards/jwt-auth.guard';
import { UserFavoritesService } from './favorites.service';

/**
 * Authenticated endpoints for the private favorite-idea collection.
 *
 * Favorites may contain ideas generated by the user and ideas the user
 * accepted from Discover.
 *
 * @author Eman
 */
@Controller('users')
@UseGuards(JwtAuthGuard)
export class UserFavoritesController {
  constructor(private readonly favoritesService: UserFavoritesService) {}

  /** Adds an owned or accepted idea to private favorites. */
  @Post('ideas/:ideaId/favorite')
  addFavorite(
    @CurrentUser() user: { id: string },
    @Param('ideaId', ParseUUIDPipe) ideaId: string,
  ) {
    return this.favoritesService.addFavorite(user.id, ideaId);
  }

  /** Removes one idea from private favorites. */
  @Delete('ideas/:ideaId/favorite')
  removeFavorite(
    @CurrentUser() user: { id: string },
    @Param('ideaId', ParseUUIDPipe) ideaId: string,
  ) {
    return this.favoritesService.removeFavorite(user.id, ideaId);
  }

  /** Returns all owned and accepted favorites for the current user. */
  @Get('favorites')
  getFavorites(@CurrentUser() user: { id: string }) {
    return this.favoritesService.getFavorites(user.id);
  }
}