import { RequestWorkflowIntentProfileUtil } from './request-workflow-intent-profile.util';
import { RequestOperationalCostAttributionUtil } from './request-operational-cost-attribution.util';

export type RequestWorkflowArchetype =
  | 'CONSUMER_SOFTWARE'
  | 'DEVELOPER_TECHNICAL'
  | 'FINANCIAL_TRANSACTION_OPERATIONS'
  | 'ECOMMERCE_PROFITABILITY_OPERATIONS'
  | 'SUBSCRIPTION_REVENUE_RETENTION_OPERATIONS'
  | 'MEDIA_CONTENT_PROFITABILITY_OPERATIONS'
  | 'TRANSPORTATION_PROFITABILITY_OPERATIONS'
  | 'LOGISTICS_PROFITABILITY_OPERATIONS'
  | 'RESTAURANT_DELIVERY_FRAUD_OPERATIONS'
  | 'TRANSACTION_ACCOUNT_ABUSE_OPERATIONS'
  | 'FACILITY_RESOURCE_MONITORING_OPERATIONS'
  | 'DIGITAL_TRUST_SAFETY_OPERATIONS'
  | 'ACCOUNT_ACCESS_SECURITY_OPERATIONS'
  | 'ENTERPRISE_IDENTITY_ACCESS_SECURITY_OPERATIONS'
  | 'ACADEMIC_PLATFORM_SECURITY_OPERATIONS'
  | 'PROPERTY_ASSET_PERFORMANCE_OPERATIONS'
  | 'BUILDING_ENVIRONMENTAL_MONITORING_OPERATIONS'
  | 'URBAN_MOBILITY_OPERATIONS'
  | 'URBAN_ENERGY_DEMAND_OPERATIONS'
  | 'GOVERNMENT_RECORD_SECURITY_OPERATIONS'
  | 'CUSTOM_COMMISSION_APPROVAL_OPERATIONS'
  | 'PHYSICAL_LOCAL_SERVICE_OPERATIONS'
  | 'RENTAL_INVENTORY_OPERATIONS'
  | 'MANUFACTURING_COST_PROFITABILITY_OPERATIONS'
  | 'INDUSTRIAL_ENERGY_EQUIPMENT_HEALTH_OPERATIONS'
  | 'RENEWABLE_ASSET_PERFORMANCE_OPERATIONS'
  | 'INDUSTRIAL_SUPPLY_CHAIN_OPERATIONS'
  | 'AGRICULTURAL_SUPPLY_CHAIN_OPERATIONS'
  | 'AGRICULTURAL_DISTRIBUTION_PROFITABILITY_OPERATIONS'
  | 'AGRICULTURAL_EXPORT_PROFITABILITY_OPERATIONS'
  | 'FARM_ENERGY_OPERATIONS'
  | 'COMMERCIAL_BUILDING_ENERGY_OPERATIONS'
  | 'CONNECTED_ASSET_SECURITY_OPERATIONS'
  | 'PROFESSIONAL_EVIDENCE_RECORDS_OPERATIONS'
  | 'PROFESSIONAL_SERVICE_AGENCY_OPERATIONS'
  | 'RESTAURANT_ENERGY_OPERATIONS'
  | 'CONNECTED_EQUIPMENT_MAINTENANCE_OPERATIONS'
  | 'FOOD_STORAGE_CONDITION_OPERATIONS'
  | 'RESTORATION_CONSERVATION_OPERATIONS'
  | 'RESIDENTIAL_CLEANING_OPERATIONS'
  | 'HEALTHCARE_COST_RESOURCE_EFFICIENCY_OPERATIONS'
  | 'HEALTHCARE_INSTITUTIONAL_OPERATIONS'
  | 'ACADEMIC_INSTITUTIONAL_OPERATIONS'
  | 'ENTERPRISE_POLICY_COMPLIANCE_OPERATIONS'
  | 'TOURISM_DESTINATION_OPERATIONS'
  | 'PUBLIC_SECTOR_OPERATIONS'
  | 'OPERATIONAL_COST_ATTRIBUTION_OPERATIONS'
  | 'MUNICIPAL_WASTE_COLLECTION_OPERATIONS'
  | 'MUSICAL_MANUSCRIPT_RESTORATION_OPERATIONS'
  | 'GENERAL_OPERATIONAL';

export type RequestWorkflowArchetypeResult = {
  readonly archetype: RequestWorkflowArchetype;
  readonly confidence: number;
  readonly preferredSourceKeys: readonly string[];
  readonly blockedSourceKeys: readonly string[];
};

export class RequestWorkflowArchetypeUtil {
  static classify(_input: {
    readonly requestDescription?: string | null;
    readonly plannedQueries?: readonly string[];
    readonly intentConcepts?: readonly string[];
    readonly selectedDomainNames?: readonly string[];
  }): RequestWorkflowArchetypeResult {
    return {
      archetype: 'GENERAL_OPERATIONAL',
      confidence: 0,
      preferredSourceKeys: [],
      blockedSourceKeys: [],
    };
  }

  static sourceFocusFor(
    _archetype: RequestWorkflowArchetype,
  ): readonly ('REVIEWS' | 'FORUMS' | 'TECHNICAL' | 'NEWS' | 'PRODUCT_DISCOVERY')[] {
    return [];
  }
}
