export type RequestCollectionSourceFocus =
  | 'REVIEWS'
  | 'FORUMS'
  | 'TECHNICAL'
  | 'NEWS'
  | 'PRODUCT_DISCOVERY';

export type RequestCollectionDomainSelectionMode = 'EXISTING' | 'NEW';

export type RequestIntentMode =
  | 'EXPLICIT_PROBLEM'
  | 'EXPLICIT_PROBLEM_DISCOVERY'
  | 'DISCOVERY_INTENT';

export type RequestIntentInterpretation = {
  /**
   * EXPLICIT_PROBLEM_DISCOVERY means the requester supplied a concrete problem
   * example while describing the domain/workflow context. It is soft discovery
   * context only: it may help resolve domains, actors, vocabulary, and later
   * solution design, but it never constrains which evidence-backed problem wins.
   * EXPLICIT_PROBLEM remains reserved for an internal post-evidence corroboration
   * pass after a verified canonical problem family already exists.
   */
  readonly mode: RequestIntentMode;
  /** Concise text/domain discovery scope. It constrains retrieval but is never evidence. */
  readonly summary: string;
  /**
   * Requester-stated problem hypothesis for EXPLICIT_PROBLEM_DISCOVERY, or the
   * internally locked evidence-selected family for EXPLICIT_PROBLEM.
   */
  readonly explicitProblem: string | null;
  /** Optional requester goal/capability hint. It never determines the winning problem. */
  readonly desiredOutcome: string | null;
};

export type RequestCollectionSourcePlan = {
  readonly sourceKey: string;
  readonly queries: readonly string[];
  readonly routingHints: readonly string[];
  /** Domain lane that caused this source/query probe to run. Retrieval provenance only. */
  readonly discoveryDomainId?: string | null;
  readonly discoveryDomainName?: string | null;
  /** Candidate discovery lanes covered by this source call. Same collector may serve multiple domains. */
  readonly discoveryDomainIds?: readonly string[];
  readonly discoveryDomainNames?: readonly string[];
  /** Stable query-intent identifier used to trace evidence back to its search decision. */
  readonly queryIntentId?: string | null;
  /** Source budget tier. Every admin-enabled collector may run, but low-fit sources remain micro probes. */
  readonly sourceTier?: 'PRIMARY' | 'SECONDARY' | 'MICRO_PROBE';
  /** Canonical problem facets this query is attempting to validate. */
  readonly problemFacetIds?: readonly string[];
};

export type RequestCollectionDomainIdentity = {
  readonly actor: string;
  readonly object: string;
  readonly workflow: string;
  readonly failure: string;
};

export type RequestCausalSearchProbe = {
  /**
   * Retrieval-only relation angle generated by PREPARING AI. It never becomes
   * evidence or a causal claim by itself; downstream semantic adjudication
   * remains authoritative.
   */
  readonly relationType:
    | 'STATED_CAUSE'
    | 'FAILURE_CHAIN'
    | 'OBSERVED_SYMPTOM'
    | 'CONSEQUENCE'
    | 'PRACTITIONER_LANGUAGE'
    | 'DOCUMENTARY_LANGUAGE';
  /** Human-searchable query anchored to the immutable requester scope. */
  readonly query: string;
};

/**
 * Retrieval-only semantic profile used to keep query/source planning grounded
 * in the supplied text. It is not the canonical software problem and must never
 * outrank evidence. The final problem family is selected only from trusted
 * collected evidence.
 *
 * EXPLICIT_PROBLEM_DISCOVERY keeps requester wording as soft domain/workflow
 * discovery and product-design context only. Evidence remains free to select a
 * different stronger problem inside the resolved domain. EXPLICIT_PROBLEM is
 * reserved for internal corroboration of an already evidence-selected family.
 */
export type RequestCanonicalProblemProfile = {
  readonly actor: string;
  readonly object: string;
  readonly coreProblem: string;
  readonly workflow: string;
  /** Canonical request friction, kept separate from downstream consequences. */
  readonly friction?: string;
  readonly failureModes: readonly string[];
  readonly consequences: readonly string[];
  /** Safe deterministic aliases used only for retrieval recall, never as evidence claims. */
  readonly actorAliases?: readonly string[];
  readonly objectAliases?: readonly string[];
  readonly evidenceFacets?: readonly string[];
};

export type RequestCollectionPlan = {
  /**
   * Exact active domain classification selected by the AI from the complete
   * active catalog. Hidden and visible domains are both visible to the model for
   * TEXT_ONLY classification. With requester-selected domains, those exact rows
   * remain authoritative and the broader catalog is classification context only.
   */
  readonly selectedExistingDomainId?: string | null;

  /**
   * Whether the AI reused an existing active domain or proposed a new hidden
   * domain for the current request.
   */
  readonly domainSelectionMode?: RequestCollectionDomainSelectionMode;

  readonly suggestedDomainName: string | null;

  /**
   * Request-grounded semantic scopes that materially participate in the
   * described workflow but are not promoted to configured domain rows.
   *
   * Example: a text-only Construction Management request may explicitly
   * involve Insurance and Equipment Rental. Those concepts must remain
   * available to retrieval, recovery, analytics, and prompt grounding even
   * when they are not present in the admin domain catalog. They are retrieval
   * facets only; they are never evidence and never create domain records.
   */
  readonly inferredSecondaryScopes?: readonly string[];

  readonly requestIntent?: RequestIntentInterpretation;
  readonly domainIdentity?: RequestCollectionDomainIdentity;
  readonly problemProfile?: RequestCanonicalProblemProfile;
  readonly existingDomainMatchScore?: number;
  readonly searchQueries: readonly string[];
  /**
   * AI-proposed practitioner/research terminology used only to improve recall.
   * These phrases are retrieval vocabulary, never evidence and never a problem
   * claim. Runtime queries anchor them back to the immutable requester scope.
   */
  readonly retrievalVocabulary?: readonly string[];
  /**
   * AI-generated retrieval probes. In initial DISCOVERY_INTENT they are optional
   * text-grounded search angles only; in internal EXPLICIT_PROBLEM mode they
   * corroborate the already evidence-selected family. They never become evidence
   * or define the winning problem by themselves.
   */
  readonly causalSearchProbes?: readonly RequestCausalSearchProbe[];
  readonly evidenceTargets: readonly string[];
  readonly intentConcepts: readonly string[];
  readonly sourceFocus: readonly RequestCollectionSourceFocus[];
  readonly selectedSourceKeys?: readonly string[];
  readonly sourcePlans?: readonly RequestCollectionSourcePlan[];
  readonly confidence: number;
  readonly aiUsed: boolean;
  readonly fallbackUsed: boolean;
};
