import { BadRequestException, Injectable } from '@nestjs/common';

import {
  DomainResolutionSource,
  LanguageCode,
  PreferenceCategory,
  Prisma,
} from '@prisma/client';

import { PrismaService } from '../../../prisma/prisma.service';
import { inferDominantRequestDomainName } from '../utils/request-domain-inference.util';

/**
 * Result returned after resolving one concrete domain
 * for an idea-generation request.
 */
export type DomainResolutionCandidate = {
  readonly domainId: string;
  readonly domainName: string;
  readonly score: number;
  readonly reasons: readonly string[];
};

export type DomainResolutionTrace = {
  /** Human-readable explanation of why this domain was selected. */
  readonly reasons: readonly string[];

  /** Saved preferences that directly participated in domain resolution. */
  readonly matchedInterests: readonly string[];

  /** Bounded ranked alternatives used for explainability and cross-domain scope expansion. */
  readonly candidates: readonly DomainResolutionCandidate[];
};

export type DomainResolutionResult = {
  /** Resolved active domain identifier. */
  readonly domainId: string;

  /** Resolved active domain name. */
  readonly domainName: string;

  /** Strategy that produced the selected domain. */
  readonly source: DomainResolutionSource;

  /** Confidence score between zero and one. */
  readonly confidence: number;

  /** Explainability metadata; it never changes pipeline decisions. */
  readonly trace: DomainResolutionTrace;
};

/**
 * Input used to resolve one concrete domain.
 */
type ResolveDomainInput = {
  /** Authenticated user identifier, when available. */
  readonly userId?: string;

  /** Domain explicitly selected by the requester. */
  readonly domainId?: string;

  /** Natural-language description supplied by the requester. */
  readonly description?: string;

  /** Keywords supplied with the generation request. */
  readonly keywords?: readonly string[];

  /** Professional domain proposed by the pre-collection intent planner. */
  readonly plannedDomainName?: string;

  /** Search concepts and evidence targets proposed before collection. */
  readonly plannedKeywords?: readonly string[];

  /** Requested generation language. */
  readonly language: LanguageCode;
};

type DomainCandidate = {
  readonly id: string;
  readonly name: string;
  readonly isVisible: boolean;
  readonly isAutoGenerated: boolean;
  readonly domainKeywords: readonly {
    readonly keyword: string;
  }[];
};

/**
 * Weighted domain score inferred from a user's historical actions.
 */
type HistoricalDomainScore = {
  readonly domainId: string;
  score: number;
};

/**
 * Resolves exactly one active, concrete domain for an idea-generation request.
 *
 * Resolution priority:
 * 1. Explicit concrete domain selected by the requester, while the current
 *    description may add strongly matched cross-domain search candidates.
 * 2. Description and keywords supplied with the current request.
 * 3. A weighted blend of saved domain preferences, favorite ideas, and recent
 *    generation history when the request contains no current domain/description.
 * 4. A deterministic system-wide domain fallback.
 *
 * The final fallback selects the least-used active concrete domain rather than
 * choosing randomly. This keeps results reproducible and improves domain
 * diversity across the platform.
 *
 * @author Malak
 */
@Injectable()
export class DomainResolutionService {
  private static readonly GENERATED_IDEA_WEIGHT = 3;
  private static readonly FAVORITE_IDEA_WEIGHT = 5;
  private static readonly MAX_HISTORY_RECORDS_PER_SIGNAL = 100;

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Resolves one active concrete domain for the supplied request.
   *
   * A General domain is treated as an instruction to continue automatic
   * resolution rather than as a concrete generation domain.
   */
  async resolve(input: ResolveDomainInput): Promise<DomainResolutionResult> {
    const hasCurrentRequest = this.hasRequestSearchInput(
      input.description,
      input.keywords,
    );
    const [selectedDomainResult, currentRequestDomains] = await Promise.all([
      this.resolveSelectedDomain(input.domainId),
      hasCurrentRequest
        ? this.loadConcreteDomains(input.language, true)
        : Promise.resolve(null),
    ]);

    if (selectedDomainResult) {
      if (!hasCurrentRequest || !currentRequestDomains) {
        return selectedDomainResult;
      }

      const requestMatch = this.resolveByKeywords(
        currentRequestDomains,
        input.description,
        input.keywords,
      );

      if (!requestMatch) {
        return selectedDomainResult;
      }

      const mergedCandidates = [
        ...requestMatch.trace.candidates,
        ...selectedDomainResult.trace.candidates,
      ]
        .filter(
          (candidate, index, candidates) =>
            candidates.findIndex(
              (item) => item.domainId === candidate.domainId,
            ) === index,
        )
        .slice(0, 3);

      return {
        ...selectedDomainResult,
        trace: {
          reasons: [
            ...selectedDomainResult.trace.reasons,
            'The current description was also analyzed so strongly matched additional domains can participate as cross-domain search constraints without replacing the explicitly selected primary domain.',
          ],
          matchedInterests: [],
          candidates: mergedCandidates,
        },
      };
    }

    const domains =
      currentRequestDomains ??
      (await this.loadConcreteDomains(input.language, false));

    /*
     * Explicit request text has priority over stored personalization because it
     * represents the user's current intent. If the request describes a domain
     * that is not configured yet, create a concrete active domain and persist
     * the same request terms as domain keywords. This keeps the next run fast
     * and prevents an unrelated preference/history fallback from replacing the
     * user's current problem scope.
     */
    if (hasCurrentRequest) {
      const requestText = [
        input.description ?? '',
        ...(input.keywords ?? []),
        ...(input.plannedKeywords ?? []),
      ]
        .join(' ')
        .normalize('NFKC')
        .toLocaleLowerCase();
      const plannedDomainName = this.normalizePlannedDomainName(
        input.plannedDomainName,
      );
      const canonicalRequestDomainName = this.inferKnownDomainName(requestText);
      const inferredKnownDomainName = this.chooseRequestDomainName(
        canonicalRequestDomainName,
        plannedDomainName,
      );
      const inferredKnownDomain = inferredKnownDomainName
        ? domains.find(
            (domain) =>
              this.normalizeSemanticText(domain.name) ===
              this.normalizeSemanticText(inferredKnownDomainName),
          )
        : undefined;

      if (inferredKnownDomain) {
        return {
          domainId: inferredKnownDomain.id,
          domainName: inferredKnownDomain.name,
          source: DomainResolutionSource.KEYWORD_MATCH,
          confidence: 0.96,
          trace: {
            reasons: [
              plannedDomainName
                ? 'The pre-collection intent planner analyzed the requester workflow before collection; a stable canonical domain mapping is reused when available so equivalent requests do not create duplicate actor-style domains.'
                : 'The current request matched a canonical semantic domain before generic database-keyword scoring, preventing unrelated stored auto-domain keywords from overriding the requester intent.',
              `Matched request domain: ${inferredKnownDomain.name}`,
            ],
            matchedInterests: [],
            candidates: [
              {
                domainId: inferredKnownDomain.id,
                domainName: inferredKnownDomain.name,
                score: 1,
                reasons: ['Canonical semantic request-domain match'],
              },
            ],
          },
        };
      }

      if (inferredKnownDomainName) {
        const createdKnownDomain = await this.resolveOrCreateRequestDomain(input);
        if (createdKnownDomain) {
          return createdKnownDomain;
        }
      }

      if (domains.length > 0) {
        const keywordResult = this.resolveByKeywords(
          domains,
          input.description,
          input.keywords,
        );

        if (keywordResult) {
          return keywordResult;
        }
      }

      const createdDomainResult = await this.resolveOrCreateRequestDomain(input);
      if (createdDomainResult) {
        return createdDomainResult;
      }
    }

    if (domains.length === 0) {
      throw new BadRequestException('No active concrete domain is configured.');
    }

    /*
     * These personalization reads are independent. Load them in one database
     * latency window, then blend their normalized scores in memory. This keeps
     * the no-input path personalized without adding sequential database latency.
     */
    const [
      preferredDomainResult,
      favoriteDomainResult,
      historicalDomainResult,
    ] = await Promise.all([
      this.resolvePreferredDomain(input.userId, domains),
      this.resolveFromFavorites(input.userId, domains),
      this.resolveFromGeneratedHistory(input.userId, domains),
    ]);

    const personalizedDomainResult = this.combinePersonalizationSignals(
      domains,
      preferredDomainResult,
      favoriteDomainResult,
      historicalDomainResult,
    );

    if (personalizedDomainResult) {
      return personalizedDomainResult;
    }

    return this.resolveSystemFallback(domains);
  }

  /** Loads all active concrete domains and their matching keywords. */
  private async loadConcreteDomains(
    language: LanguageCode,
    includeHidden: boolean,
  ): Promise<DomainCandidate[]> {
    const domains = await this.prisma.domain.findMany({
      where: {
        isActive: true,
        ...(includeHidden ? {} : { isVisible: true }),
      },
      select: {
        id: true,
        name: true,
        isVisible: true,
        isAutoGenerated: true,
        domainKeywords: {
          where: {
            language: {
              in: [language, LanguageCode.ANY],
            },
          },
          select: {
            keyword: true,
          },
        },
      },
      orderBy: {
        name: 'asc',
      },
    });

    return domains.filter(
      (domain) =>
        !this.isGeneral(domain.name) &&
        (!domain.isAutoGenerated ||
          domain.isVisible ||
          this.isSemanticallyUsableHiddenAutoDomain(domain)),
    );
  }

  /**
   * Resolves an explicitly selected domain.
   *
   * Selecting General continues automatic resolution.
   */
  private async resolveSelectedDomain(
    domainId?: string,
  ): Promise<DomainResolutionResult | null> {
    const normalizedDomainId = domainId?.trim();

    if (!normalizedDomainId) {
      return null;
    }

    const selectedDomain = await this.prisma.domain.findUnique({
      where: {
        id: normalizedDomainId,
      },
      select: {
        id: true,
        name: true,
        isActive: true,
        isVisible: true,
      },
    });

    if (!selectedDomain || !selectedDomain.isActive || !selectedDomain.isVisible) {
      throw new BadRequestException('The selected domain is unavailable.');
    }

    if (this.isGeneral(selectedDomain.name)) {
      return null;
    }

    return {
      domainId: selectedDomain.id,
      domainName: selectedDomain.name,
      source: DomainResolutionSource.USER_SELECTED,
      confidence: 1,
      trace: {
        reasons: ['The requester explicitly selected this domain.'],
        matchedInterests: [],
        candidates: [
          {
            domainId: selectedDomain.id,
            domainName: selectedDomain.name,
            score: 1,
            reasons: ['Explicit requester selection'],
          },
        ],
      },
    };
  }

  /**
   * Blends the user's long-lived personalization signals instead of stopping at
   * the first source that returns a value. Saved preferences remain the strongest
   * signal, favorites refine ties and durable intent, and recent generation
   * history supplies a smaller behavioral prior.
   *
   * Each source is normalized independently before weighting so a user with many
   * historical ideas cannot numerically overwhelm an explicit saved preference.
   * The method is in-memory only and therefore adds no database latency beyond
   * the three reads that already execute in parallel.
   */
  private combinePersonalizationSignals(
    domains: readonly DomainCandidate[],
    preferredDomainResult: DomainResolutionResult | null,
    favoriteDomainResult: DomainResolutionResult | null,
    historicalDomainResult: DomainResolutionResult | null,
  ): DomainResolutionResult | null {
    const signals = [
      {
        key: 'saved preferences',
        weight: 0.5,
        result: preferredDomainResult,
      },
      {
        key: 'favorite ideas',
        weight: 0.3,
        result: favoriteDomainResult,
      },
      {
        key: 'recent generation history',
        weight: 0.2,
        result: historicalDomainResult,
      },
    ] as const;

    const totals = new Map<
      string,
      {
        score: number;
        reasons: string[];
        matchedInterests: string[];
        sources: Set<string>;
      }
    >();

    for (const signal of signals) {
      const candidates = signal.result?.trace.candidates ?? [];
      const maxScore = Math.max(
        0,
        ...candidates.map((candidate) => candidate.score),
      );

      if (maxScore <= 0) {
        continue;
      }

      for (const candidate of candidates) {
        const contribution =
          signal.weight * Math.max(0, candidate.score) / maxScore;
        if (contribution <= 0) {
          continue;
        }

        const current = totals.get(candidate.domainId) ?? {
          score: 0,
          reasons: [],
          matchedInterests: [],
          sources: new Set<string>(),
        };

        current.score += contribution;
        current.sources.add(signal.key);
        current.reasons.push(
          `${signal.key} contributed ${(contribution * 100).toFixed(1)} weighted points.`,
        );

        if (
          signal.result?.domainId === candidate.domainId &&
          signal.result.trace.matchedInterests.length > 0
        ) {
          current.matchedInterests.push(
            ...signal.result.trace.matchedInterests,
          );
        }

        totals.set(candidate.domainId, current);
      }
    }

    const domainById = new Map(domains.map((domain) => [domain.id, domain]));
    const ordered = [...totals.entries()]
      .map(([domainId, value]) => ({
        domainId,
        domainName: domainById.get(domainId)?.name ?? domainId,
        score: value.score,
        reasons: value.reasons,
        matchedInterests: value.matchedInterests,
        sources: value.sources,
      }))
      .filter((candidate) => domainById.has(candidate.domainId))
      .sort(
        (first, second) =>
          second.score - first.score ||
          first.domainName.localeCompare(second.domainName),
      );

    const winner = ordered[0];
    if (!winner) {
      return null;
    }

    const runnerUpScore = ordered[1]?.score ?? 0;
    const margin = Math.max(0, winner.score - runnerUpScore);
    const confidence = Math.min(
      0.95,
      0.68 + Math.min(0.2, winner.score * 0.2) + Math.min(0.07, margin * 0.2),
    );
    const preferenceBacked =
      preferredDomainResult?.trace.candidates.some(
        (candidate) => candidate.domainId === winner.domainId,
      ) ?? false;

    return {
      domainId: winner.domainId,
      domainName: winner.domainName,
      source: preferenceBacked
        ? DomainResolutionSource.USER_PREFERENCE
        : DomainResolutionSource.USER_HISTORY,
      confidence,
      trace: {
        reasons: [
          `Selected from blended personalization signals: ${[...winner.sources].join(', ')}.`,
          'Saved preferences, favorites, and recent generation history are normalized independently so no high-volume history source can overwhelm explicit user intent.',
        ],
        matchedInterests: [...new Set(winner.matchedInterests)],
        candidates: ordered.slice(0, 3).map((candidate) => ({
          domainId: candidate.domainId,
          domainName: candidate.domainName,
          score: Number(candidate.score.toFixed(4)),
          reasons: [...new Set(candidate.reasons)],
        })),
      },
    };
  }

  /**
   * Resolves a domain from both the legacy preference JSON and the structured
   * preference catalog selections.
   */
  private async resolvePreferredDomain(
    userId: string | undefined,
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult | null> {
    if (!userId) {
      return null;
    }

    const [preference, selections] = await Promise.all([
      this.prisma.userPreference.findUnique({
        where: {
          userId,
        },
        select: {
          preferredDomains: true,
        },
      }),
      this.prisma.userPreferenceSelection.findMany({
        where: {
          userId,
          preferenceOption: {
            category: PreferenceCategory.DOMAIN,
            isActive: true,
          },
        },
        select: {
          preferenceOption: {
            select: {
              key: true,
              name: true,
            },
          },
        },
        orderBy: {
          selectedAt: 'asc',
        },
      }),
    ]);

    const preferredValues = [
      ...this.readStringArray(preference?.preferredDomains),
      ...selections.flatMap(({ preferenceOption }) => [
        preferenceOption.key,
        preferenceOption.name,
      ]),
    ];

    const matchedDomain = this.findFirstMatchingDomain(
      domains,
      preferredValues,
    );

    if (!matchedDomain) {
      return null;
    }

    const matchedInterests = preferredValues.filter((value) => {
      const normalizedValue = this.normalizeComparableValue(value);
      return (
        matchedDomain.id === value ||
        this.normalizeComparableValue(matchedDomain.name) === normalizedValue
      );
    });

    const preferenceCandidates = domains
      .map((domain) => {
        const matchingValues = preferredValues.filter((value) => {
          const normalizedValue = this.normalizeComparableValue(value);
          return (
            domain.id === value ||
            this.normalizeComparableValue(domain.name) === normalizedValue
          );
        });

        return {
          domainId: domain.id,
          domainName: domain.name,
          score: matchingValues.length,
          reasons: matchingValues.map(
            (value) => `Matches saved domain preference: ${value}`,
          ),
        };
      })
      .filter((candidate) => candidate.score > 0)
      .sort(
        (first, second) =>
          second.score - first.score ||
          first.domainName.localeCompare(second.domainName),
      )
      .slice(0, 3);

    return {
      domainId: matchedDomain.id,
      domainName: matchedDomain.name,
      source: DomainResolutionSource.USER_PREFERENCE,
      confidence: 0.9,
      trace: {
        reasons: [
          'Selected from the authenticated user\'s saved domain interests before using behavioral history or the system fallback.',
        ],
        matchedInterests: [...new Set(matchedInterests)],
        candidates: preferenceCandidates,
      },
    };
  }

  /**
   * Resolves the strongest domain from the user's favorite ideas.
   * Favorites are an explicit long-lived preference signal and therefore run
   * before generated-idea history when no current request/domain was supplied.
   */
  private async resolveFromFavorites(
    userId: string | undefined,
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult | null> {
    if (!userId) {
      return null;
    }

    const domainIds = domains.map((domain) => domain.id);
    const favorites = await this.prisma.favoriteIdea.findMany({
      where: {
        userId,
        idea: {
          deletedAt: null,
          domainId: { in: domainIds },
        },
      },
      select: {
        idea: { select: { domainId: true } },
      },
      orderBy: { createdAt: 'desc' },
      take: DomainResolutionService.MAX_HISTORY_RECORDS_PER_SIGNAL,
    });

    const scores = new Map<string, HistoricalDomainScore>();
    for (const favorite of favorites) {
      this.addHistoricalScore(
        scores,
        favorite.idea.domainId,
        DomainResolutionService.FAVORITE_IDEA_WEIGHT,
      );
    }

    return this.buildHistoryResolution(
      domains,
      scores,
      0.84,
      'The user did not provide a current problem/domain, so favorite-idea history selected the most explicitly preferred domain.',
      'Favorite idea history',
    );
  }

  /**
   * Resolves the domain the user most often generates ideas for. This is used
   * only after current request text, selected domains, saved preferences, and
   * favorites have produced no usable signal.
   */
  private async resolveFromGeneratedHistory(
    userId: string | undefined,
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult | null> {
    if (!userId) {
      return null;
    }

    const domainIds = domains.map((domain) => domain.id);
    const generatedIdeas = await this.prisma.idea.findMany({
      where: {
        userId,
        deletedAt: null,
        domainId: { in: domainIds },
      },
      select: { domainId: true },
      orderBy: { createdAt: 'desc' },
      take: DomainResolutionService.MAX_HISTORY_RECORDS_PER_SIGNAL,
    });

    const scores = new Map<string, HistoricalDomainScore>();
    for (const idea of generatedIdeas) {
      this.addHistoricalScore(
        scores,
        idea.domainId,
        DomainResolutionService.GENERATED_IDEA_WEIGHT,
      );
    }

    return this.buildHistoryResolution(
      domains,
      scores,
      0.72,
      "No current request, saved preference, or favorite-domain signal was available, so the user's recent generation history selected the domain.",
      'Recent generated-idea history',
    );
  }

  /** Converts weighted history signals into one deterministic domain result. */
  private buildHistoryResolution(
    domains: readonly DomainCandidate[],
    scores: ReadonlyMap<string, HistoricalDomainScore>,
    confidence: number,
    reason: string,
    candidateReason: string,
  ): DomainResolutionResult | null {
    const domainById = new Map(domains.map((domain) => [domain.id, domain]));
    const ordered = [...scores.values()]
      .filter((item) => domainById.has(item.domainId))
      .sort((first, second) => {
        const scoreDifference = second.score - first.score;
        if (scoreDifference !== 0) return scoreDifference;
        return (domainById.get(first.domainId)?.name ?? '').localeCompare(
          domainById.get(second.domainId)?.name ?? '',
        );
      });

    const best = ordered[0];
    if (!best) return null;

    const selectedDomain = domainById.get(best.domainId);
    if (!selectedDomain) return null;

    return {
      domainId: selectedDomain.id,
      domainName: selectedDomain.name,
      source: DomainResolutionSource.USER_HISTORY,
      confidence,
      trace: {
        reasons: [reason],
        matchedInterests: [],
        candidates: ordered.slice(0, 3).map((item) => ({
          domainId: item.domainId,
          domainName: domainById.get(item.domainId)?.name ?? item.domainId,
          score: item.score,
          reasons: [candidateReason],
        })),
      },
    };
  }

  /** Adds one weighted signal to a domain history score. */
  private addHistoricalScore(
    scores: Map<string, HistoricalDomainScore>,
    domainId: string,
    weight: number,
  ): void {
    const existing = scores.get(domainId);

    if (existing) {
      existing.score += weight;
      return;
    }

    scores.set(domainId, {
      domainId,
      score: weight,
    });
  }

  /**
   * Resolves the best domain using the current request text.
   *
   * Null is returned when no domain term matches, allowing safe fallback to
   * preferences and user history instead of rejecting the request.
   */
  private resolveByKeywords(
    domains: readonly DomainCandidate[],
    description?: string,
    keywords?: readonly string[],
  ): DomainResolutionResult | null {
    const rawSearchText = [description ?? '', ...(keywords ?? [])]
      .join(' ')
      .trim();

    if (!rawSearchText) {
      return null;
    }

    const normalizedSearchText = this.normalizeSemanticText(rawSearchText);
    const searchTokens = new Set(
      normalizedSearchText.split(/\s+/).filter(Boolean),
    );
    const genericTokens = new Set([
      'management',
      'operations',
      'operation',
      'business',
      'company',
      'system',
      'platform',
      'software',
      'application',
      'workflow',
      'service',
      'services',
      'data',
      'digital',
      'often',
      'usually',
      'frequently',
      'commonly',
      'struggle',
      'struggles',
      'struggling',
      'keep',
      'keeps',
      'keeping',
      'owner',
      'owners',
      'people',
      'staff',
      'user',
      'users',
      'information',
      'different',
      'multiple',
      'several',
      'difficulty',
      'difficult',
      'planning',
      'tracking',
      'transportation',
      'budget',
      'schedule',
      'schedules',
      'documents',
    ]);

    const rankedDomains = domains
      .map((domain) => {
        const configuredTerms = [
          domain.name,
          ...domain.domainKeywords.map((item) => item.keyword),
          ...this.getDomainIntentAliases(domain.name),
        ]
          .map((term) => this.normalizeSemanticText(term))
          .filter(Boolean);

        let score = 0;
        const reasons: string[] = [];

        for (const term of [...new Set(configuredTerms)]) {
          const termTokens = term.split(/\s+/).filter(Boolean);
          const specificTermTokens = termTokens.filter(
            (token) => !genericTokens.has(token),
          );

          if (specificTermTokens.length === 0) {
            continue;
          }

          const matchedTokens = termTokens.filter((token) =>
            searchTokens.has(token),
          );
          const matchedSpecificTokens = specificTermTokens.filter((token) =>
            searchTokens.has(token),
          );
          const exactPhraseMatch = this.containsWholeSemanticPhrase(normalizedSearchText, term);
          const specificCoverage =
            matchedSpecificTokens.length / specificTermTokens.length;
          const hiddenAutoDomainRequiresStrongMatch =
            domain.isAutoGenerated && !domain.isVisible;

          if (
            hiddenAutoDomainRequiresStrongMatch &&
            !(
              (exactPhraseMatch && specificTermTokens.length >= 2) ||
              (matchedSpecificTokens.length >= 2 && specificCoverage >= 0.75)
            )
          ) {
            continue;
          }

          if (exactPhraseMatch) {
            const exactWeight = Math.max(3, specificTermTokens.length * 3);
            score += exactWeight;
            reasons.push(`Matched request phrase: ${term}`);
            continue;
          }

          if (matchedTokens.length === 0) {
            continue;
          }

          if (
            matchedTokens.every((token) => genericTokens.has(token)) ||
            (
              termTokens.length > 1 &&
              matchedTokens.length === 1 &&
              matchedTokens[0] === 'ai'
            )
          ) {
            continue;
          }

          if (termTokens.length > 1 && matchedSpecificTokens.length < 2) {
            continue;
          }

          const coverage =
            matchedSpecificTokens.length / specificTermTokens.length;

          if (
            coverage >= 0.6 ||
            (termTokens.length === 1 && matchedSpecificTokens.length === 1)
          ) {
            const tokenWeight =
              matchedSpecificTokens.length * 2 + (coverage === 1 ? 1 : 0);
            score += tokenWeight;
            reasons.push(
              `Matched request terms: ${matchedSpecificTokens.join(', ')}`,
            );
          }
        }

        return {
          domain,
          score,
          reasons: [...new Set(reasons)].slice(0, 4),
        };
      })
      .sort(
        (first, second) =>
          second.score - first.score ||
          first.domain.name.localeCompare(second.domain.name),
      );

    const bestMatch = rankedDomains[0];

    if (!bestMatch || bestMatch.score < 4) {
      return null;
    }

    const secondBestScore = rankedDomains[1]?.score ?? 0;
    const lead = Math.max(0, bestMatch.score - secondBestScore);

    if (secondBestScore >= 4 && lead < 2 && bestMatch.score < 8) {
      return null;
    }

    const confidence = Math.min(
      0.97,
      0.68 + Math.min(0.2, bestMatch.score * 0.02) + Math.min(0.08, lead * 0.02),
    );

    return {
      domainId: bestMatch.domain.id,
      domainName: bestMatch.domain.name,
      source: DomainResolutionSource.KEYWORD_MATCH,
      confidence,
      trace: {
        reasons: [
          'The current request intent matched this domain more strongly than stored preferences or historical behavior.',
          ...bestMatch.reasons,
        ],
        matchedInterests: [],
        candidates: rankedDomains
          .filter((candidate) => candidate.score > 0)
          .slice(0, 3)
          .map((candidate) => ({
            domainId: candidate.domain.id,
            domainName: candidate.domain.name,
            score: candidate.score,
            reasons:
              candidate.reasons.length > 0
                ? candidate.reasons
                : ['Matched normalized current-request terms'],
          })),
      },
    };
  }

  private containsWholeSemanticPhrase(
    normalizedSearchText: string,
    normalizedTerm: string,
  ): boolean {
    if (!normalizedSearchText || !normalizedTerm) {
      return false;
    }

    return (` ${normalizedSearchText} `).includes(` ${normalizedTerm} `);
  }

  private normalizeSemanticText(value: string): string {
    const aliases: Readonly<Record<string, string>> = {
      financial: 'finance',
      finances: 'finance',
      financing: 'finance',
      administration: 'administrative',
      admin: 'administrative',
      companies: 'business',
      company: 'business',
      businesses: 'business',
      invoicing: 'invoice',
      invoices: 'invoice',
      expenses: 'expense',
      budgeting: 'budget',
      budgets: 'budget',
      reconciliations: 'reconciliation',
      payments: 'payment',
      payrolls: 'payroll',
      procurements: 'procurement',
      employees: 'employee',
      workers: 'worker',
      recruiters: 'recruiter',
      recruiting: 'recruitment',
      hires: 'hiring',
      hired: 'hiring',
      workloads: 'workload',
      costs: 'cost',
      spending: 'expense',
      expenditures: 'expense',
      records: 'record',
      feedbacks: 'feedback',
      breaches: 'breach',
      threats: 'threat',
      attacks: 'attack',
      alerts: 'alert',
      incidents: 'incident',
      credentials: 'credential',
      vulnerabilities: 'vulnerability',
      bands: 'band',
      musicians: 'musician',
      rehearsals: 'rehearsal',
      recordings: 'recording',
      songs: 'song',
      setlists: 'setlist',
      devices: 'device',
    };

    return value
      .trim()
      .toLowerCase()
      .normalize('NFKC')
      .replace(/[^\p{L}\p{N}]+/gu, ' ')
      .split(/\s+/)
      .filter(Boolean)
      .map((token) => aliases[token] ?? token)
      .join(' ');
  }

  private getDomainIntentAliases(domainName: string): readonly string[] {
    const normalizedDomain = this.normalizeComparableValue(domainName);

    if (normalizedDomain === 'finance') {
      return [
        'financial management',
        'financial administration',
        'administrative finance',
        'finance operations',
        'business finance',
        'accounting',
        'bookkeeping',
        'invoice management',
        'expense management',
        'budget management',
        'payroll',
        'procurement',
        'reconciliation',
        'cash flow',
        'back office finance',
      ];
    }

    if (normalizedDomain === 'business operations') {
      return [
        'administration',
        'administrative operations',
        'business operations',
        'company operations',
        'office administration',
        'approval workflow',
        'document workflow',
        'back office operations',
        'internal operations',
        'manual administration',
        'workflow bottleneck',
      ];
    }

    if (
      normalizedDomain === 'tattoo studio operations client management' ||
      normalizedDomain === 'tattoo studio operations & client management' ||
      normalizedDomain === 'tattoo studio management'
    ) {
      return [
        'tattoo studio operations',
        'tattoo artist scheduling',
        'tattoo appointment booking',
        'tattoo booking conflicts',
        'tattoo design revisions',
        'tattoo client feedback',
        'tattoo client preferences',
        'tattoo appointment deposits',
        'tattoo consent forms',
        'tattoo aftercare instructions',
        'tattoo client session history',
        'tattoo studio calendar',
        'tattoo design approval history',
        'tattoo client records',
      ];
    }

    if (
      normalizedDomain === 'shipment traceability chain of custody management' ||
      normalizedDomain === 'shipment traceability & chain of custody management' ||
      normalizedDomain === 'logistics'
    ) {
      return [
        'shipment tracking',
        'high value shipment tracking',
        'shipment chain of custody',
        'shipment handover records',
        'carrier handover tracking',
        'warehouse shipment records',
        'customs checkpoint records',
        'shipment location updates',
        'shipment temperature telemetry',
        'delivery confirmation records',
        'shipment dispute resolution',
        'supply chain partner accountability',
        'shipment event reconciliation',
        'proof of delivery',
      ];
    }

    if (
      normalizedDomain === 'recipe culinary knowledge management' ||
      normalizedDomain === 'recipe & culinary knowledge management' ||
      normalizedDomain === 'personal recipe management'
    ) {
      return [
        'recipe collection',
        'saved recipes',
        'recipe search',
        'ingredient substitutions',
        'recipe modifications',
        'personal recipe changes',
        'cooking results',
        'family recipe preferences',
        'recipe notes',
        'recipe history',
        'cooking notes',
        'recipe version history',
      ];
    }

    if (
      normalizedDomain === 'travel planning comparison' ||
      normalizedDomain === 'travel planning & comparison'
    ) {
      return [
        'travel planning',
        'accommodation comparison',
        'travel price comparison',
        'booking platform comparison',
        'activity availability',
        'transportation options',
        'travel reviews',
        'traveler preferences',
        'trip budget planning',
        'local experiences',
      ];
    }

    if (
      normalizedDomain === 'book club reading group management' ||
      normalizedDomain === 'book club & reading group management' ||
      normalizedDomain === 'reading community coordination'
    ) {
      return [
        'book club',
        'reading group',
        'reading schedule',
        'member reading progress',
        'book club meeting',
        'meeting coordination',
        'discussion topics',
        'discussion history',
        'shared reading notes',
        'book suggestions',
        'reading progress tracking',
        'missed meeting catch up',
      ];
    }

    if (
      normalizedDomain === 'photography studio operations' ||
      normalizedDomain === 'photography workflow management' ||
      normalizedDomain === 'photography studios'
    ) {
      return [
        'photography studio',
        'photo studio',
        'client booking',
        'photo shoot scheduling',
        'shoot schedule',
        'shot list',
        'equipment preparation',
        'camera gear checklist',
        'editing request',
        'image selection',
        'photo selection',
        'gallery selection',
        'client delivery deadline',
        'photo delivery',
        'studio project workflow',
      ];
    }

    if (
      normalizedDomain === 'beauty salon management' ||
      normalizedDomain === 'salon management' ||
      normalizedDomain === 'beauty services' ||
      normalizedDomain === 'personal care services'
    ) {
      return [
        'beauty salon',
        'salon management',
        'salon appointments',
        'appointment scheduling',
        'stylist availability',
        'client preferences',
        'service history',
        'loyalty history',
        'salon inventory',
        'product usage',
        'special requests',
        'double booking',
        'beauty services',
        'personal care services',
      ];
    }

    if (
      normalizedDomain === 'hr recruitment' ||
      normalizedDomain === 'human resources' ||
      normalizedDomain === 'human resources recruitment'
    ) {
      return [
        'human resources',
        'hr',
        'recruitment',
        'hiring',
        'employee',
        'employees',
        'workforce',
        'worker',
        'staff',
        'employee burnout',
        'workplace burnout',
        'employee turnover',
        'staff turnover',
        'retention',
        'candidate screening',
        'applicant tracking',
        'talent acquisition',
        'employee onboarding',
        'employee feedback',
        'hr records',
        'workforce management',
        'workload',
      ];
    }

    if (
      normalizedDomain === 'cybersecurity' ||
      normalizedDomain === 'cyber security' ||
      normalizedDomain === 'information security'
    ) {
      return [
        'cybersecurity',
        'cyber security',
        'information security',
        'security',
        'data security',
        'patient data security',
        'unauthorized access',
        'unauthorised access',
        'access control',
        'data breach',
        'security breach',
        'suspicious activity',
        'security alert',
        'security alerts',
        'threat detection',
        'security monitoring',
        'incident response',
        'cyber attack',
        'cyberattack',
        'malware',
        'ransomware',
        'phishing',
        'vulnerability',
        'credential theft',
        'identity access',
        'authentication security',
        'privacy breach',
        'sensitive data',
      ];
    }

    if (normalizedDomain === 'artificial intelligence') {
      return [
        'artificial intelligence',
        'machine learning',
        'generative ai',
        'ai model',
        'model inference',
        'ai reliability',
        'model hallucination',
        'prompt reliability',
      ];
    }

    if (
      normalizedDomain === 'wardrobe personal fashion management' ||
      normalizedDomain === 'wardrobe fashion management' ||
      normalizedDomain === 'personal wardrobe management' ||
      normalizedDomain === 'digital wardrobe'
    ) {
      return [
        'wardrobe management',
        'digital wardrobe',
        'clothing inventory',
        'clothes inventory',
        'closet organization',
        'shoes and accessories inventory',
        'outfit planning',
        'outfit coordination',
        'clothing fit tracking',
        'clothing cleaning tracking',
        'clothing repair tracking',
        'wardrobe maintenance',
        'shopping receipt wardrobe import',
        'duplicate clothing purchase prevention',
        'seasonal outfit planning',
        'weather based outfit planning',
      ];
    }

    if (
      normalizedDomain === 'tailoring custom apparel' ||
      normalizedDomain === 'tailoring' ||
      normalizedDomain === 'custom apparel'
    ) {
      return [
        'tailoring',
        'tailor shop',
        'custom clothing',
        'custom apparel',
        'customer measurements',
        'body measurements',
        'fabric selection',
        'alteration request',
        'clothing alterations',
        'fitting appointment',
        'design notes',
        'custom order tracking',
        'garment order',
        'made to measure',
        'bespoke clothing',
      ];
    }

    if (
      normalizedDomain === 'pet care management' ||
      normalizedDomain === 'pet care' ||
      normalizedDomain === 'animal care'
    ) {
      return [
        'pet care management',
        'pet health records',
        'vaccination tracking',
        'grooming schedule',
        'feeding routine',
        'pet care coordination',
        'veterinary care history',
        'veterinarian records',
        'pet sitter instructions',
        'shared pet care',
        'pet appointment tracking',
        'animal care records',
      ];
    }

    if (
      normalizedDomain === 'event planning management' ||
      normalizedDomain === 'event planning' ||
      normalizedDomain === 'wedding event management' ||
      normalizedDomain === 'wedding planning'
    ) {
      return [
        'event planning',
        'wedding planning',
        'private event planning',
        'event coordination',
        'wedding coordination',
        'venue coordination',
        'vendor coordination',
        'photographer scheduling',
        'decorator scheduling',
        'catering coordination',
        'guest list management',
        'event budget tracking',
        'event schedule management',
        'last minute event changes',
        'booking conflict prevention',
      ];
    }

    if (
      normalizedDomain === 'funeral memorial services' ||
      normalizedDomain === 'memorial services' ||
      normalizedDomain === 'funeral services'
    ) {
      return [
        'funeral service coordination',
        'memorial service coordination',
        'ceremony scheduling',
        'burial preference tracking',
        'funeral home coordination',
        'guest communication',
        'floral arrangement coordination',
        'family request tracking',
        'memorial transportation coordination',
        'funeral document checklist',
        'bereavement service planning',
      ];
    }

    if (normalizedDomain === 'sports fitness' || normalizedDomain === 'sports and fitness') {
      return [
        'sports training',
        'athlete performance',
        'training load monitoring',
        'overtraining detection',
        'athlete recovery',
        'injury risk monitoring',
        'wearable workout data',
        'fitness equipment telemetry',
        'coach performance dashboard',
      ];
    }

    if (normalizedDomain === 'internet of things' || normalizedDomain === 'iot') {
      return [
        'connected devices',
        'sensor monitoring',
        'device telemetry',
        'device management',
        'edge devices',
        'wearable devices',
        'connected equipment',
        'device protocol compatibility',
      ];
    }

    if (normalizedDomain === 'real estate') {
      return [
        'property data',
        'property records',
        'real estate listings',
        'rental listings',
        'housing search',
        'lease management',
        'property management',
        'real estate data integration',
      ];
    }

    if (normalizedDomain === 'tourism') {
      return [
        'travel planning',
        'travel booking',
        'tourist services',
        'destination management',
        'visitor experience',
        'hotel booking',
      ];
    }

    if (normalizedDomain === 'media entertainment' || normalizedDomain === 'media and entertainment') {
      return [
        'content creation',
        'streaming',
        'audience engagement',
        'media workflow',
        'digital publishing',
        'creator workflow',
        'band rehearsal',
        'music rehearsal',
        'song version management',
        'set list coordination',
        'recording version management',
        'music collaboration',
        'rehearsal scheduling',
      ];
    }

    if (normalizedDomain === 'government' || normalizedDomain === 'public sector') {
      return [
        'government agency',
        'government department',
        'public administration',
        'citizen service',
        'permit application',
        'license processing',
        'official record',
        'public record',
        'approval status',
        'ownership record',
      ];
    }

    if (
      normalizedDomain === 'legaltech' ||
      normalizedDomain === 'legal tech' ||
      normalizedDomain === 'legal technology'
    ) {
      return [
        'legal research',
        'legal document',
        'contract verification',
        'case management',
        'ownership record',
        'record verification',
        'document verification',
        'legal workflow',
        'dispute resolution',
      ];
    }

    if (normalizedDomain === 'blockchain' || normalizedDomain === 'web3') {
      return [
        'blockchain',
        'distributed ledger',
        'smart contract',
        'tamper evident record',
        'record provenance',
        'immutable record',
        'version integrity',
        'audit trail',
      ];
    }

    if (normalizedDomain === 'agriculture') {
      return [
        'agriculture',
        'farming',
        'crop monitoring',
        'crop health',
        'crop disease detection',
        'soil monitoring',
        'soil telemetry',
        'weather forecasting',
        'field prioritization',
        'irrigation scheduling',
        'harvest planning',
        'agricultural resource optimization',
      ];
    }

    if (normalizedDomain === 'e commerce' || normalizedDomain === 'ecommerce') {
      return [
        'online commerce',
        'online store',
        'shopping',
        'checkout',
        'merchant',
        'order management',
      ];
    }

    if (normalizedDomain === 'agriculture') {
      return [
        'farming',
        'farm management',
        'irrigation',
        'crop management',
        'crop monitoring',
        'soil',
        'harvest',
        'agricultural operations',
      ];
    }

    if (normalizedDomain === 'energy') {
      return [
        'electricity',
        'solar',
        'power grid',
        'energy consumption',
        'energy monitoring',
        'battery',
        'utility',
        'power management',
      ];
    }

    if (
      normalizedDomain === 'dance studio operations & performance management'
    ) {
      return [
        'dance studio',
        'class scheduling',
        'instructor availability',
        'student attendance',
        'choreography progress',
        'costume requirements',
        'rehearsal tracking',
        'performance readiness',
      ];
    }

    if (normalizedDomain === 'education') {
      return [
        'learning',
        'teaching',
        'student',
        'students',
        'school',
        'university',
        'homework',
        'assignment',
        'coursework',
        'classroom',
        'grading',
      ];
    }

    if (normalizedDomain === 'healthcare') {
      return ['health', 'medical', 'clinic', 'patient', 'hospital'];
    }

    return [];
  }

  /**
   * Creates a concrete domain when current request text does not match any
   * configured domain. The operation is idempotent and stores a compact search
   * vocabulary so subsequent collection runs can reuse it immediately.
   */
  private async resolveOrCreateRequestDomain(
    input: ResolveDomainInput,
  ): Promise<DomainResolutionResult | null> {
    const requestText = [
      input.description ?? '',
      ...(input.keywords ?? []),
      ...(input.plannedKeywords ?? []),
    ].join(' ');
    const canonicalRequestDomainName = this.inferKnownDomainName(requestText);
    const plannedDomainName = this.normalizePlannedDomainName(
      input.plannedDomainName,
    );
    const domainName =
      this.chooseRequestDomainName(canonicalRequestDomainName, plannedDomainName) ??
      this.inferDomainName(input.description, input.keywords);
    if (!domainName || this.isGeneral(domainName)) {
      return null;
    }

    const keywordCandidates = this.buildAutoDomainKeywords(
      input.description,
      input.keywords,
      domainName,
      input.plannedKeywords,
    );

    const persistDomain = () =>
      this.prisma.$transaction(async (transaction) => {
        const existing = await transaction.domain.findFirst({
          where: {
            name: { equals: domainName, mode: 'insensitive' },
          },
          select: {
            id: true,
            name: true,
            isActive: true,
            isVisible: true,
            isAutoGenerated: true,
          },
        });

        if (existing && !existing.isActive) {
          return null;
        }

        const resolved = existing
          ? existing
          : await transaction.domain.create({
              data: {
                name: domainName,
                isActive: true,
                isVisible: false,
                isAutoGenerated: true,
              },
              select: {
                id: true,
                name: true,
                isActive: true,
                isVisible: true,
                isAutoGenerated: true,
              },
            });

        if (!resolved) {
          return null;
        }

        if (keywordCandidates.length > 0) {
          await transaction.domainKeyword.createMany({
            data: keywordCandidates.map((keyword) => ({
              domainId: resolved.id,
              keyword,
              language: input.language,
            })),
            skipDuplicates: true,
          });
        }

        return resolved;
      });

    let domain: Awaited<ReturnType<typeof persistDomain>>;
    try {
      domain = await persistDomain();
      if (!domain) {
        return null;
      }
    } catch (error: unknown) {
      /*
       * Two simultaneous unmatched requests can infer the same new domain.
       * Treat the unique-name race as success and reuse the winner instead of
       * surfacing a transient database error to idea generation.
       */
      if (
        !(
          error instanceof Prisma.PrismaClientKnownRequestError &&
          error.code === 'P2002'
        )
      ) {
        throw error;
      }

      const racedDomain = await this.prisma.domain.findFirst({
        where: { name: { equals: domainName, mode: 'insensitive' } },
        select: {
          id: true,
          name: true,
          isActive: true,
          isVisible: true,
          isAutoGenerated: true,
        },
      });
      if (!racedDomain) throw error;
      if (!racedDomain.isActive) return null;

      domain = racedDomain;

      if (keywordCandidates.length > 0) {
        await this.prisma.domainKeyword.createMany({
          data: keywordCandidates.map((keyword) => ({
            domainId: racedDomain.id,
            keyword,
            language: input.language,
          })),
          skipDuplicates: true,
        });
      }
    }

    if (!domain) {
      return null;
    }

    return {
      domainId: domain.id,
      domainName: domain.name,
      source: DomainResolutionSource.KEYWORD_MATCH,
      confidence: 0.72,
      trace: {
        reasons: [
          input.plannedDomainName
            ? 'The pre-collection intent planner identified a professional domain that was not configured yet, so a hidden active internal domain was created before evidence collection instead of using an unrelated personalized fallback.'
            : 'The current request did not match an existing domain strongly enough, so a new active internal domain was created from the requester intent instead of falling back to unrelated personalization. The domain is hidden from user selection until an administrator publishes it.',
          `Stored ${keywordCandidates.length} request-derived search keyword(s) for future collection.`,
        ],
        matchedInterests: [],
        candidates: [
          {
            domainId: domain.id,
            domainName: domain.name,
            score: 1,
            reasons: ['Auto-created from unmatched current-request intent'],
          },
        ],
      },
    };
  }

  private normalizePlannedDomainName(value?: string): string | null {
    const normalized = value
      ?.normalize('NFKC')
      .replace(/\s+/gu, ' ')
      .replace(/[.!?]+$/gu, '')
      .trim();

    if (!normalized || normalized.length > 80) return null;
    const words = normalized.split(/\s+/u);
    if (words.length < 2 || words.length > 8) return null;
    if (
      /^(?:people|users|companies|travelers|travellers|members|owners|teams?|students?)\b/iu.test(
        normalized,
      ) ||
      /\b(?:often|struggle|struggles|want to|need to|who|regularly)\b/iu.test(
        normalized,
      )
    ) {
      return null;
    }

    return normalized;
  }

  /** Derives a stable short domain label from unmatched request text. */
  private inferDomainName(
    description?: string,
    keywords?: readonly string[],
  ): string | null {
    const requestText = [description ?? '', ...(keywords ?? [])]
      .join(' ')
      .normalize('NFKC')
      .toLowerCase();
    const knownDomain = this.inferKnownDomainName(requestText);
    if (knownDomain) return knownDomain;

    const stopWords = new Set([
      'a', 'an', 'and', 'are', 'about', 'for', 'from', 'in', 'into', 'is', 'of',
      'on', 'or', 'the', 'to', 'with', 'without', 'problem', 'problems', 'issue',
      'issues', 'need', 'needs', 'want', 'wants', 'software', 'system', 'app',
      'application', 'platform', 'user', 'users', 'using', 'use', 'help', 'make',
      'improve', 'solution', 'solutions', 'often', 'usually', 'frequently',
      'commonly', 'struggle', 'struggles', 'struggling', 'difficult', 'difficulty',
      'keep', 'keeps', 'keeping', 'track', 'tracking', 'several', 'multiple',
      'many', 'different', 'exactly', 'months', 'later', 'when', 'where', 'which',
      'because', 'across', 'among', 'shared', 'responsibility', 'information',
      'حل', 'مشكلة', 'مشاكل', 'في', 'من', 'على', 'عن', 'مع', 'بدون', 'مستخدم',
      'مستخدمين', 'تطبيق', 'نظام',
    ]);

    const source = [
      ...(keywords ?? []),
      description ?? '',
    ]
      .join(' ')
      .normalize('NFKC')
      .toLowerCase()
      .replace(/[^\p{L}\p{N}]+/gu, ' ')
      .split(/\s+/u)
      .filter(Boolean)
      .filter((token) => token.length >= 3 && !stopWords.has(token));

    const unique = [...new Set(source)].slice(0, 3);
    if (unique.length === 0) return null;

    return unique
      .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
      .join(' ')
      .slice(0, 80);
  }

  /**
   * Maps common requester vocabulary to a canonical domain name even when the
   * corresponding domain row does not exist yet. This avoids creating labels
   * such as "Students Homework" when the actual missing domain is Education.
   */
  private chooseRequestDomainName(
    canonicalDomainName: string | null,
    plannedDomainName: string | null,
  ): string | null {
    if (!plannedDomainName) return canonicalDomainName;
    if (!canonicalDomainName) return plannedDomainName;

    const canonical = this.normalizeSemanticText(canonicalDomainName);
    const planned = this.normalizeSemanticText(plannedDomainName);
    if (canonical === planned) return canonicalDomainName;

    const broadCanonicalDomains = new Set([
      'education',
      'business operations',
      'government',
      'logistics',
      'healthcare',
      'tourism',
      'media entertainment',
      'sports fitness',
    ]);

    return broadCanonicalDomains.has(canonical)
      ? plannedDomainName
      : canonicalDomainName;
  }

  private inferKnownDomainName(requestText: string): string | null {
    return inferDominantRequestDomainName(requestText);
  }

  /** Builds bounded, search-friendly keywords for an auto-created domain. */
  private buildAutoDomainKeywords(
    description: string | undefined,
    keywords: readonly string[] | undefined,
    domainName: string,
    plannedKeywords?: readonly string[],
  ): string[] {
    const normalized = [
      ...(plannedKeywords ?? []),
      domainName,
      ...this.getDomainIntentAliases(domainName),
      ...(keywords ?? []),
      ...(description ? [description] : []),
    ]
      .map((value) =>
        value
          .normalize('NFKC')
          .toLowerCase()
          .replace(/[^\p{L}\p{N}]+/gu, ' ')
          .replace(/\s+/gu, ' ')
          .trim(),
      )
      .filter(Boolean);

    const genericSearchTokens = new Set([
      'problem', 'problems', 'issue', 'issues', 'need', 'needs', 'software',
      'system', 'application', 'platform', 'often', 'usually', 'frequently',
      'commonly', 'struggle', 'struggles', 'struggling', 'keep', 'keeping',
      'owners', 'owner', 'users', 'user', 'people', 'staff', 'months', 'later',
      'different', 'several', 'multiple', 'exactly', 'because', 'information',
      'difficulty', 'difficult', 'causing', 'cause', 'delayed', 'delay',
      'care', 'management', 'health', 'records', 'tracking', 'planning',
      'transportation', 'budget', 'schedules', 'documents', 'large', 'numbers',
      'still', 'remember', 'what', 'they', 'have', 'their', 'only', 'memory',
      'items', 'pieces', 'specific', 'leading', 'usually', 'kept',
    ]);

    const tokenCandidates = normalized
      .flatMap((value) => value.split(' '))
      .filter((value) => value.length >= 4)
      .filter((value) => !genericSearchTokens.has(value));

    const phraseCandidates = normalized
      .filter((value) => value.split(' ').length <= 6)
      .filter(
        (value) =>
          !value
            .split(' ')
            .every((token) => genericSearchTokens.has(token)),
      )
      .slice(0, 12);

    return [...new Set([...phraseCandidates, ...tokenCandidates])].slice(0, 14);
  }

  /**
   * Selects a deterministic system fallback.
   *
   * The least-used active concrete domain is chosen to avoid permanently
   * favoring the first database row and to improve platform-wide diversity.
   */
  private async resolveSystemFallback(
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult> {
    const usage = await this.prisma.idea.groupBy({
      by: ['domainId'],
      where: {
        deletedAt: null,
        domainId: {
          in: domains.map((domain) => domain.id),
        },
      },
      _count: {
        _all: true,
      },
    });

    const usageByDomainId = new Map(
      usage.map((item) => [item.domainId, item._count._all]),
    );

    const selectedDomain = [...domains].sort((first, second) => {
      const firstUsage = usageByDomainId.get(first.id) ?? 0;
      const secondUsage = usageByDomainId.get(second.id) ?? 0;

      return firstUsage - secondUsage || first.name.localeCompare(second.name);
    })[0];

    if (!selectedDomain) {
      throw new BadRequestException('No active concrete domain is configured.');
    }

    return {
      domainId: selectedDomain.id,
      domainName: selectedDomain.name,
      source: DomainResolutionSource.SYSTEM_DEFAULT,
      confidence: 0.25,
      trace: {
        reasons: [
          'No explicit request, saved domain preference, or usable user-history signal was available; the deterministic least-used-domain fallback was used.',
        ],
        matchedInterests: [],
        candidates: [
          {
            domainId: selectedDomain.id,
            domainName: selectedDomain.name,
            score: 0.25,
            reasons: ['Deterministic system fallback'],
          },
        ],
      },
    };
  }

  /** Returns true when the request contains meaningful text or keywords. */
  private hasRequestSearchInput(
    description?: string,
    keywords?: readonly string[],
  ): boolean {
    return Boolean(
      description?.trim() || keywords?.some((keyword) => keyword.trim()),
    );
  }

  /** Finds the first active domain matching an ID, name, or normalized key. */
  private findFirstMatchingDomain(
    domains: readonly DomainCandidate[],
    values: readonly string[],
  ): DomainCandidate | null {
    for (const value of values) {
      const normalizedValue = this.normalizeComparableValue(value);

      if (!normalizedValue) {
        continue;
      }

      const matchingDomain = domains.find(
        (domain) =>
          domain.id === value ||
          this.normalizeComparableValue(domain.name) === normalizedValue,
      );

      if (matchingDomain) {
        return matchingDomain;
      }
    }

    return null;
  }

  /** Normalizes catalog keys and domain names for stable comparison. */
  private normalizeComparableValue(value: string): string {
    return value
      .trim()
      .toLowerCase()
      .replace(/[-_&]+/g, ' ')
      .replace(/\s+/g, ' ');
  }

  /**
   * Rejects hidden auto-generated domains whose persisted label is mostly made
   * of generic sentence words. These rows may remain in the database for audit
   * history, but they must never poison future request matching.
   */
  private isSemanticallyUsableHiddenAutoDomain(
    domain: DomainCandidate,
  ): boolean {
    const genericNameTokens = new Set([
      'often',
      'usually',
      'frequently',
      'commonly',
      'struggle',
      'struggles',
      'struggling',
      'keep',
      'keeps',
      'keeping',
      'owner',
      'owners',
      'people',
      'staff',
      'user',
      'users',
      'management',
      'operations',
      'operation',
      'system',
      'platform',
      'software',
      'application',
      'workflow',
      'service',
      'services',
      'data',
      'digital',
      'information',
      'different',
      'multiple',
      'several',
      'difficulty',
      'difficult',
      'tracking',
    ]);
    const nameTokens = this.normalizeSemanticText(domain.name)
      .split(/\s+/u)
      .filter(Boolean);
    const specificNameTokens = nameTokens.filter(
      (token) => token.length >= 3 && !genericNameTokens.has(token),
    );

    if (specificNameTokens.length < 1) {
      return false;
    }

    return !/\b(?:often|usually|frequently|commonly|struggle|struggles|struggling|keep|keeps|keeping)\b/iu.test(
      domain.name,
    );
  }

  /** Determines whether a domain is a generic non-concrete category. */
  private isGeneral(name: string): boolean {
    const normalizedName = name.trim().toLowerCase();

    return ['general', 'عام', 'all'].includes(normalizedName);
  }

  /** Safely converts a Prisma JSON value into a clean string array. */
  private readStringArray(
    value: Prisma.JsonValue | null | undefined,
  ): string[] {
    if (!Array.isArray(value)) {
      return [];
    }

    return value
      .filter((item): item is string => typeof item === 'string')
      .map((item) => item.trim())
      .filter(Boolean);
  }
}