import { BadRequestException, Injectable } from '@nestjs/common';

import {
  DomainResolutionSource,
  LanguageCode,
  PreferenceCategory,
  Prisma,
} from '@prisma/client';

import { PrismaService } from '../../../prisma/prisma.service';
import { inferDominantRequestDomainName } from '../utils/request-domain-inference.util';
import { RequestQueryProvenanceUtil } from '../utils/request-query-provenance.util';
import { RequestNicheCustomCraftUtil } from '../utils/request-niche-custom-craft.util';

/**
 * Result returned after resolving one concrete domain
 * for an idea-generation request.
 */
export type DomainResolutionCandidate = {
  readonly domainId: string;
  readonly domainName: string;
  readonly score: number;
  readonly reasons: readonly string[];
};

export type DomainResolutionTrace = {
  /** Human-readable explanation of why this domain was selected. */
  readonly reasons: readonly string[];

  /** Saved preferences that directly participated in domain resolution. */
  readonly matchedInterests: readonly string[];

  /** Bounded ranked alternatives used for explainability and cross-domain scope expansion. */
  readonly candidates: readonly DomainResolutionCandidate[];
};

export type DomainResolutionResult = {
  /** Resolved active domain identifier. */
  readonly domainId: string;

  /** Resolved active domain name. */
  readonly domainName: string;

  /** Strategy that produced the selected domain. */
  readonly source: DomainResolutionSource;

  /** Confidence score between zero and one. */
  readonly confidence: number;

  /** Explainability metadata; it never changes pipeline decisions. */
  readonly trace: DomainResolutionTrace;
};

/**
 * Input used to resolve one concrete domain.
 */
type ResolveDomainInput = {
  /** Authenticated user identifier, when available. */
  readonly userId?: string;

  /** Domain explicitly selected by the requester. */
  readonly domainId?: string;

  /** Natural-language description supplied by the requester. */
  readonly description?: string;

  /** Keywords supplied with the generation request. */
  readonly keywords?: readonly string[];

  /** Existing active domain id explicitly selected by the AI domain classifier. */
  readonly plannedExistingDomainId?: string;

  /** Whether the AI selected an existing domain or proposed a new hidden one. */
  readonly plannedDomainSelectionMode?: 'EXISTING' | 'NEW';

  /** Professional domain proposed by the pre-collection intent planner. */
  readonly plannedDomainName?: string;

  /** Confidence from the AI pre-collection planner when its domain label was model-generated. */
  readonly plannedDomainConfidence?: number;

  /** Search concepts and evidence targets proposed before collection. */
  readonly plannedKeywords?: readonly string[];

  /** Requested generation language. */
  readonly language: LanguageCode;
};

type DomainCandidate = {
  readonly id: string;
  readonly name: string;
  readonly isVisible: boolean;
  readonly isAutoGenerated: boolean;
  readonly domainKeywords: readonly {
    readonly keyword: string;
  }[];
};

/**
 * Weighted domain score inferred from a user's historical actions.
 */
type HistoricalDomainScore = {
  readonly domainId: string;
  score: number;
};

/**
 * Resolves exactly one active, concrete domain for an idea-generation request.
 *
 * Resolution priority:
 * 1. Explicit concrete domain selected by the requester, while the current
 *    description may add strongly matched cross-domain search candidates.
 * 2. Description and keywords supplied with the current request.
 * 3. Saved domain preferences when no current domain/description exists.
 * 4. Favorite-idea domains when no saved preference exists.
 * 5. The domains the user most frequently generates when neither preference
 *    nor favorite history provides a usable signal.
 * 6. A deterministic system-wide domain fallback.
 *
 * The final fallback selects the least-used active concrete domain rather than
 * choosing randomly. This keeps results reproducible and improves domain
 * diversity across the platform.
 *
 * @author Malak
 */
@Injectable()
export class DomainResolutionService {
  private static readonly GENERATED_IDEA_WEIGHT = 3;
  private static readonly FAVORITE_IDEA_WEIGHT = 5;
  private static readonly MAX_HISTORY_RECORDS_PER_SIGNAL = 100;

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Resolves one active concrete domain for the supplied request.
   *
   * A General domain is treated as an instruction to continue automatic
   * resolution rather than as a concrete generation domain.
   */
  async resolve(input: ResolveDomainInput): Promise<DomainResolutionResult> {
    const hasCurrentRequest = this.hasRequestSearchInput(
      input.description,
      input.keywords,
    );
    const normalizedPlannedDomainConfidence =
      this.normalizePlannedDomainConfidence(input.plannedDomainConfidence);
    const hasAuthoritativeAiPlan =
      hasCurrentRequest &&
      (input.plannedDomainSelectionMode === 'EXISTING' ||
        input.plannedDomainSelectionMode === 'NEW') &&
      normalizedPlannedDomainConfidence >= 0.7;

    /*
     * A validated PREPARING-stage AI domain decision should not pay for a full
     * visible+hidden catalog scan a second time. Verify the exact planned
     * domain and any explicitly selected domain concurrently; fall back to the
     * complete catalog only when that plan cannot be safely resolved.
     */
    if (hasAuthoritativeAiPlan) {
      const [plannedDomainResult, explicitDomainResult] = await Promise.all([
        this.resolveAiPlannedDomain(input),
        this.resolveSelectedDomain(input.domainId),
      ]);
      if (plannedDomainResult) {
        if (
          explicitDomainResult &&
          explicitDomainResult.domainId !== plannedDomainResult.domainId
        ) {
          return {
            ...plannedDomainResult,
            trace: {
              reasons: [
                ...plannedDomainResult.trace.reasons,
                `The explicitly selected domain "${explicitDomainResult.domainName}" remains a first-class cross-domain constraint while the PREPARING AI domain remains the semantic primary.`,
              ],
              matchedInterests: [],
              candidates: [
                ...plannedDomainResult.trace.candidates,
                ...explicitDomainResult.trace.candidates,
              ]
                .filter(
                  (candidate, index, candidates) =>
                    candidates.findIndex(
                      (item) => item.domainId === candidate.domainId,
                    ) === index,
                )
                .slice(0, 4),
            },
          };
        }
        return plannedDomainResult;
      }
    }

    const [selectedDomainResult, currentRequestDomains] = await Promise.all([
      this.resolveSelectedDomain(input.domainId),
      hasCurrentRequest
        ? this.loadConcreteDomains(input.language, true)
        : Promise.resolve(null),
    ]);

    if (selectedDomainResult) {
      if (!hasCurrentRequest || !currentRequestDomains) {
        return selectedDomainResult;
      }

      const requestMatch = this.resolveByKeywords(
        currentRequestDomains,
        input.description,
        input.keywords,
      );
      const plannedRequestDomain = await this.resolveOrCreateRequestDomain(input);

      const supportedRequestMatchCandidates =
        requestMatch?.trace.candidates.filter((candidate) =>
          this.isStrongCrossDomainRequestMatch(
            candidate.domainName,
            input.description,
            input.keywords,
          ),
        ) ?? [];
      const semanticPrimary = plannedRequestDomain ?? selectedDomainResult;
      const mergedCandidates = [
        ...semanticPrimary.trace.candidates,
        ...selectedDomainResult.trace.candidates,
        ...supportedRequestMatchCandidates,
      ]
        .filter(
          (candidate, index, candidates) =>
            candidates.findIndex(
              (item) => item.domainId === candidate.domainId,
            ) === index,
        )
        .slice(0, 4);

      return {
        ...semanticPrimary,
        trace: {
          reasons: [
            ...(plannedRequestDomain
              ? [
                  'Because request text is present, the AI semantic domain classification is the internal primary domain used for collection and workflow resolution.',
                  `The AI classified the requester text as "${plannedRequestDomain.domainName}" after seeing the complete visible + hidden domain catalog.`,
                  `The explicitly selected domain "${selectedDomainResult.domainName}" remains a first-class cross-domain constraint and is not discarded.`,
                ]
              : selectedDomainResult.trace.reasons),
            'Explicit requester domains remain generation/search constraints even when the text belongs to a narrower hidden semantic domain.',
          ],
          matchedInterests: [],
          candidates: mergedCandidates,
        },
      };
    }

    const domains =
      currentRequestDomains ??
      (await this.loadConcreteDomains(input.language, false));

    /*
     * Explicit request text has priority over stored personalization because it
     * represents the user's current intent. If the request describes a domain
     * that is not configured yet, create a concrete active domain and persist
     * the same request terms as domain keywords. This keeps the next run fast
     * and prevents an unrelated preference/history fallback from replacing the
     * user's current problem scope.
     */
    if (hasCurrentRequest) {
      const aiResolvedDomain = await this.resolveAiPlannedDomain(input);
      if (aiResolvedDomain) {
        return aiResolvedDomain;
      }

      const requestText = [
        input.description ?? '',
        ...(input.keywords ?? []),
        ...(input.plannedKeywords ?? []),
      ]
        .join(' ')
        .normalize('NFKC')
        .toLocaleLowerCase();
      const plannedDomainName = this.normalizePlannedDomainName(
        input.plannedDomainName,
      );
      const canonicalRequestDomainName = this.inferKnownDomainName(requestText);
      const inferredKnownDomainName = this.chooseRequestDomainName(
        canonicalRequestDomainName,
        plannedDomainName,
        input.plannedDomainConfidence,
      );
      const inferredKnownDomain = inferredKnownDomainName
        ? domains.find(
            (domain) =>
              this.normalizeSemanticText(domain.name) ===
              this.normalizeSemanticText(inferredKnownDomainName),
          )
        : undefined;

      if (inferredKnownDomain) {
        return {
          domainId: inferredKnownDomain.id,
          domainName: inferredKnownDomain.name,
          source: DomainResolutionSource.KEYWORD_MATCH,
          confidence: 0.96,
          trace: {
            reasons: [
              plannedDomainName
                ? 'The pre-collection intent planner analyzed the requester workflow before collection; a stable canonical domain mapping is reused when available so equivalent requests do not create duplicate actor-style domains.'
                : 'The current request matched a canonical semantic domain before generic database-keyword scoring, preventing unrelated stored auto-domain keywords from overriding the requester intent.',
              `Matched request domain: ${inferredKnownDomain.name}`,
            ],
            matchedInterests: [],
            candidates: [
              {
                domainId: inferredKnownDomain.id,
                domainName: inferredKnownDomain.name,
                score: 1,
                reasons: ['Canonical semantic request-domain match'],
              },
            ],
          },
        };
      }

      if (inferredKnownDomainName) {
        const createdKnownDomain = await this.resolveOrCreateRequestDomain(input);
        if (createdKnownDomain) {
          return createdKnownDomain;
        }
      }

      if (domains.length > 0) {
        const keywordResult = this.resolveByKeywords(
          domains,
          input.description,
          input.keywords,
        );

        if (keywordResult) {
          return keywordResult;
        }
      }

      const createdDomainResult = await this.resolveOrCreateRequestDomain(input);
      if (createdDomainResult) {
        return createdDomainResult;
      }
    }

    if (domains.length === 0) {
      throw new BadRequestException('No active concrete domain is configured.');
    }

    /*
     * Personalization is intentionally hierarchical rather than blended.
     * A saved preference is the strongest durable statement of intent. Only
     * when no usable saved preference exists do favorites become the selector;
     * recent generated-idea history is used only when neither explicit signal
     * exists. The three reads still execute in parallel so this stricter policy
     * does not add database latency.
     */
    /*
     * Start every personalization read in parallel, but do not wait for
     * lower-priority history when the saved-preference query has already
     * produced the authoritative answer. The old Promise.all paid for the
     * slowest favorites/history query even though hierarchy rules guaranteed
     * those results could not override a preference. Attach observers so an
     * early preference return never leaves a rejected background promise
     * unhandled; if preference is absent we still await and surface the same
     * lower-priority errors as before.
     */
    const preferredDomainPromise = this.resolvePreferredDomain(
      input.userId,
      domains,
    );
    const favoriteDomainPromise = this.resolveFromFavorites(
      input.userId,
      domains,
    );
    const historicalDomainPromise = this.resolveFromGeneratedHistory(
      input.userId,
      domains,
    );
    void favoriteDomainPromise.catch(() => undefined);
    void historicalDomainPromise.catch(() => undefined);

    const preferredDomainResult = await preferredDomainPromise;
    if (preferredDomainResult) {
      return this.withPersonalizationFallbackTrace(
        preferredDomainResult,
        'saved preference',
      );
    }

    const [favoriteDomainResult, historicalDomainResult] = await Promise.all([
      favoriteDomainPromise,
      historicalDomainPromise,
    ]);

    if (favoriteDomainResult) {
      return this.withPersonalizationFallbackTrace(
        favoriteDomainResult,
        'favorite ideas',
      );
    }

    if (historicalDomainResult) {
      return this.withPersonalizationFallbackTrace(
        historicalDomainResult,
        'most frequently generated domains from recent history',
      );
    }

    return this.resolveSystemFallback(domains);
  }

  /** Loads all active concrete domains and their matching keywords. */
  private async loadConcreteDomains(
    language: LanguageCode,
    includeHidden: boolean,
  ): Promise<DomainCandidate[]> {
    const domains = await this.prisma.domain.findMany({
      where: {
        isActive: true,
        ...(includeHidden ? {} : { isVisible: true }),
      },
      select: {
        id: true,
        name: true,
        isVisible: true,
        isAutoGenerated: true,
        domainKeywords: {
          where: {
            language: {
              in: [language, LanguageCode.ANY],
            },
          },
          select: {
            keyword: true,
          },
        },
      },
      orderBy: {
        name: 'asc',
      },
    });

    return domains.filter(
      (domain) =>
        !this.isGeneral(domain.name) &&
        (!domain.isAutoGenerated ||
          domain.isVisible ||
          this.isSemanticallyUsableHiddenAutoDomain(domain)),
    );
  }

  /**
   * Resolves an explicitly selected domain.
   *
   * Selecting General continues automatic resolution.
   */
  private async resolveSelectedDomain(
    domainId?: string,
  ): Promise<DomainResolutionResult | null> {
    const normalizedDomainId = domainId?.trim();

    if (!normalizedDomainId) {
      return null;
    }

    const selectedDomain = await this.prisma.domain.findUnique({
      where: {
        id: normalizedDomainId,
      },
      select: {
        id: true,
        name: true,
        isActive: true,
        isVisible: true,
      },
    });

    if (!selectedDomain || !selectedDomain.isActive || !selectedDomain.isVisible) {
      throw new BadRequestException('The selected domain is unavailable.');
    }

    if (this.isGeneral(selectedDomain.name)) {
      return null;
    }

    return {
      domainId: selectedDomain.id,
      domainName: selectedDomain.name,
      source: DomainResolutionSource.USER_SELECTED,
      confidence: 1,
      trace: {
        reasons: ['The requester explicitly selected this domain.'],
        matchedInterests: [],
        candidates: [
          {
            domainId: selectedDomain.id,
            domainName: selectedDomain.name,
            score: 1,
            reasons: ['Explicit requester selection'],
          },
        ],
      },
    };
  }

  /**
   * Adds explainability about lower-priority personalization signals without
   * allowing them to override the selected higher-priority source.
   */
  private withPersonalizationFallbackTrace(
    selected: DomainResolutionResult,
    selectedSignal: string,
  ): DomainResolutionResult {
    return {
      ...selected,
      trace: {
        ...selected.trace,
        reasons: [
          ...selected.trace.reasons,
          `Personalization hierarchy selected ${selectedSignal}; lower-priority favorite/history signals were not allowed to override or broaden this source.`,
        ],
      },
    };
  }

  /**
   * Resolves a domain from both the legacy preference JSON and the structured
   * preference catalog selections.
   */
  private async resolvePreferredDomain(
    userId: string | undefined,
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult | null> {
    if (!userId) {
      return null;
    }

    const [preference, selections] = await Promise.all([
      this.prisma.userPreference.findUnique({
        where: {
          userId,
        },
        select: {
          preferredDomains: true,
        },
      }),
      this.prisma.userPreferenceSelection.findMany({
        where: {
          userId,
          preferenceOption: {
            category: PreferenceCategory.DOMAIN,
            isActive: true,
          },
        },
        select: {
          preferenceOption: {
            select: {
              key: true,
              name: true,
            },
          },
        },
        orderBy: {
          selectedAt: 'asc',
        },
      }),
    ]);

    const preferredValues = [
      ...this.readStringArray(preference?.preferredDomains),
      ...selections.flatMap(({ preferenceOption }) => [
        preferenceOption.key,
        preferenceOption.name,
      ]),
    ];

    const matchedDomain = this.findFirstMatchingDomain(
      domains,
      preferredValues,
    );

    if (!matchedDomain) {
      return null;
    }

    const matchedInterests = preferredValues.filter((value) => {
      const normalizedValue = this.normalizeComparableValue(value);
      return (
        matchedDomain.id === value ||
        this.normalizeComparableValue(matchedDomain.name) === normalizedValue
      );
    });

    const preferenceCandidates = domains
      .map((domain) => {
        const matchingValues = preferredValues.filter((value) => {
          const normalizedValue = this.normalizeComparableValue(value);
          return (
            domain.id === value ||
            this.normalizeComparableValue(domain.name) === normalizedValue
          );
        });

        return {
          domainId: domain.id,
          domainName: domain.name,
          score: matchingValues.length,
          reasons: matchingValues.map(
            (value) => `Matches saved domain preference: ${value}`,
          ),
        };
      })
      .filter((candidate) => candidate.score > 0)
      .sort(
        (first, second) =>
          second.score - first.score ||
          first.domainName.localeCompare(second.domainName),
      )
      .slice(0, 3);

    return {
      domainId: matchedDomain.id,
      domainName: matchedDomain.name,
      source: DomainResolutionSource.USER_PREFERENCE,
      confidence: 0.9,
      trace: {
        reasons: [
          'Selected from the authenticated user\'s saved domain interests before using behavioral history or the system fallback.',
        ],
        matchedInterests: [...new Set(matchedInterests)],
        candidates: preferenceCandidates,
      },
    };
  }

  /**
   * Resolves the strongest domain from the user's favorite ideas.
   * Favorites are an explicit long-lived preference signal and therefore run
   * before generated-idea history when no current request/domain was supplied.
   */
  private async resolveFromFavorites(
    userId: string | undefined,
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult | null> {
    if (!userId) {
      return null;
    }

    const domainIds = domains.map((domain) => domain.id);
    const favorites = await this.prisma.favoriteIdea.findMany({
      where: {
        userId,
        idea: {
          deletedAt: null,
          domainId: { in: domainIds },
        },
      },
      select: {
        idea: { select: { domainId: true } },
      },
      orderBy: { createdAt: 'desc' },
      take: DomainResolutionService.MAX_HISTORY_RECORDS_PER_SIGNAL,
    });

    const scores = new Map<string, HistoricalDomainScore>();
    for (const favorite of favorites) {
      this.addHistoricalScore(
        scores,
        favorite.idea.domainId,
        DomainResolutionService.FAVORITE_IDEA_WEIGHT,
      );
    }

    return this.buildHistoryResolution(
      domains,
      scores,
      0.84,
      'The user did not provide a current problem/domain, so favorite-idea history selected the most explicitly preferred domain.',
      'Favorite idea history',
    );
  }

  /**
   * Resolves the domain the user most often generates ideas for. This is used
   * only after current request text, selected domains, saved preferences, and
   * favorites have produced no usable signal.
   */
  private async resolveFromGeneratedHistory(
    userId: string | undefined,
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult | null> {
    if (!userId) {
      return null;
    }

    const domainIds = domains.map((domain) => domain.id);
    const generatedIdeas = await this.prisma.idea.findMany({
      where: {
        userId,
        deletedAt: null,
        domainId: { in: domainIds },
      },
      select: { domainId: true },
      orderBy: { createdAt: 'desc' },
      take: DomainResolutionService.MAX_HISTORY_RECORDS_PER_SIGNAL,
    });

    const scores = new Map<string, HistoricalDomainScore>();
    for (const idea of generatedIdeas) {
      this.addHistoricalScore(
        scores,
        idea.domainId,
        DomainResolutionService.GENERATED_IDEA_WEIGHT,
      );
    }

    return this.buildHistoryResolution(
      domains,
      scores,
      0.72,
      "No current request, saved preference, or favorite-domain signal was available, so the most frequently generated domain in the user's recent idea history was selected.",
      'Most frequently generated domain in recent history',
    );
  }

  /** Converts weighted history signals into one deterministic domain result. */
  private buildHistoryResolution(
    domains: readonly DomainCandidate[],
    scores: ReadonlyMap<string, HistoricalDomainScore>,
    confidence: number,
    reason: string,
    candidateReason: string,
  ): DomainResolutionResult | null {
    const domainById = new Map(domains.map((domain) => [domain.id, domain]));
    const ordered = [...scores.values()]
      .filter((item) => domainById.has(item.domainId))
      .sort((first, second) => {
        const scoreDifference = second.score - first.score;
        if (scoreDifference !== 0) return scoreDifference;
        return (domainById.get(first.domainId)?.name ?? '').localeCompare(
          domainById.get(second.domainId)?.name ?? '',
        );
      });

    const best = ordered[0];
    if (!best) return null;

    const selectedDomain = domainById.get(best.domainId);
    if (!selectedDomain) return null;

    return {
      domainId: selectedDomain.id,
      domainName: selectedDomain.name,
      source: DomainResolutionSource.USER_HISTORY,
      confidence,
      trace: {
        reasons: [reason],
        matchedInterests: [],
        candidates: ordered.slice(0, 3).map((item) => ({
          domainId: item.domainId,
          domainName: domainById.get(item.domainId)?.name ?? item.domainId,
          score: item.score,
          reasons: [candidateReason],
        })),
      },
    };
  }

  /** Adds one weighted signal to a domain history score. */
  private addHistoricalScore(
    scores: Map<string, HistoricalDomainScore>,
    domainId: string,
    weight: number,
  ): void {
    const existing = scores.get(domainId);

    if (existing) {
      existing.score += weight;
      return;
    }

    scores.set(domainId, {
      domainId,
      score: weight,
    });
  }

  /**
   * Resolves the best domain using the current request text.
   *
   * Null is returned when no domain term matches, allowing safe fallback to
   * preferences and user history instead of rejecting the request.
   */
  private resolveByKeywords(
    domains: readonly DomainCandidate[],
    description?: string,
    keywords?: readonly string[],
  ): DomainResolutionResult | null {
    const rawSearchText = [description ?? '', ...(keywords ?? [])]
      .join(' ')
      .trim();

    if (!rawSearchText) {
      return null;
    }

    const normalizedSearchText = this.normalizeSemanticText(rawSearchText);
    const searchTokens = new Set(
      normalizedSearchText.split(/\s+/).filter(Boolean),
    );
    const genericTokens = new Set([
      'management',
      'operations',
      'operation',
      'business',
      'company',
      'system',
      'platform',
      'software',
      'application',
      'workflow',
      'service',
      'services',
      'data',
      'digital',
      'often',
      'usually',
      'frequently',
      'commonly',
      'struggle',
      'struggles',
      'struggling',
      'keep',
      'keeps',
      'keeping',
      'owner',
      'owners',
      'people',
      'staff',
      'user',
      'users',
      'information',
      'different',
      'multiple',
      'several',
      'difficulty',
      'difficult',
      'planning',
      'tracking',
      'independent',
      'maker',
      'makers',
      'commission',
      'commissions',
      'design',
      'specification',
      'specifications',
      'custom',
      'approval',
      'domain',
      'domains',
      'antique',
      'antiques',
      'historic',
      'historical',
      'vintage',
      'preservation',
      'preserve',
      'preserved',
      'conservation',
      'conserve',
      'conserved',
      'maintenance',
      'equipment',
      'cost',
      'costs',
      'expense',
      'expenses',
      'customer',
      'customers',
      'client',
      'clients',
      'repair',
      'repairs',
      'condition',
      'history',
      'transportation',
      'budget',
      'schedule',
      'schedules',
      'documents',
      'document',
      'record',
      'records',
      'incident',
      'incidents',
      'delay',
      'delays',
      'delayed',
      'gap',
      'gaps',
      'agency',
      'agencies',
      'coordination',
      'issue',
      'issues',
      'problem',
      'problems',
      'and',
      'or',
    ]);

    const rankedDomains = domains
      .map((domain) => {
        const configuredTerms = [
          domain.name,
          ...domain.domainKeywords.map((item) => item.keyword),
          ...this.getDomainIntentAliases(domain.name),
        ]
          .map((term) => this.normalizeSemanticText(term))
          .filter(Boolean);

        let score = 0;
        const reasons: string[] = [];
        const hiddenAutoDomainRequiresStrongMatch =
          domain.isAutoGenerated && !domain.isVisible;
        const normalizedDomainName = this.normalizeSemanticText(domain.name);
        const transportSpecificDomain =
          /\b(?:fleet|freight|logistics|transport|transportation|delivery|shipment|route)\b/u.test(
            normalizedDomainName,
          );
        const requestHasTransportContext =
          /\b(?:fleet|vehicle|vehicles|freight|logistics|transport|transportation|delivery|deliveries|shipment|shipments|route|routes|courier|carrier|last mile|3pl)\b/u.test(
            normalizedSearchText,
          );
        if (transportSpecificDomain && !requestHasTransportContext) {
          return { domain, score: 0, reasons: [] };
        }
        const domainIdentityStopWords = new Set([
          ...genericTokens,
          'client',
          'clients',
          'project',
          'projects',
          'shop',
          'shops',
          'workshop',
          'workshops',
          'repair',
          'customer',
          'customers',
          // Generic workflow/outcome words must not establish identity for a
          // hidden auto-generated domain. This prevents domains such as
          // "Fitness Membership Retention & Revenue Management" from matching
          // an unrelated subscription-business request only because both talk
          // about retention and revenue.
          'analytics',
          'analysis',
          'intelligence',
          'retention',
          'revenue',
          'profitability',
          'performance',
          'forecast',
          'forecasting',
          'prediction',
          'optimization',
          'optimisation',
          'monitoring',
        ]);
        const domainIdentityTokens = this.normalizeSemanticText(domain.name)
          .split(/\s+/u)
          .filter(
            (token) =>
              token.length >= 4 && !domainIdentityStopWords.has(token),
          );
        const matchedDomainIdentityTokens = domainIdentityTokens.filter(
          (token) => searchTokens.has(token),
        );
        const requiredIdentityMatches =
          domainIdentityTokens.length <= 1 ? 1 : 2;
        const hiddenAutoDomainIdentityMatch =
          !hiddenAutoDomainRequiresStrongMatch ||
          this.containsWholeSemanticPhrase(
            normalizedSearchText,
            this.normalizeSemanticText(domain.name),
          ) ||
          matchedDomainIdentityTokens.length >= requiredIdentityMatches;

        if (!hiddenAutoDomainIdentityMatch) {
          return { domain, score: 0, reasons: [] };
        }

        if (
          normalizedDomainName === 'real estate' &&
          !/\b(?:real estate|property|properties|property management|property listings?|housing|rental|rentals|tenant|tenants|landlord|landlords|lease|leases|mortgage|mortgages|investment property|commercial property|residential property)\b/iu.test(
            normalizedSearchText,
          )
        ) {
          return { domain, score: 0, reasons: [] };
        }

        for (const term of [...new Set(configuredTerms)]) {
          const termTokens = term.split(/\s+/).filter(Boolean);
          const specificTermTokens = termTokens.filter(
            (token) => !genericTokens.has(token),
          );

          if (specificTermTokens.length === 0) {
            continue;
          }

          const matchedTokens = termTokens.filter((token) =>
            searchTokens.has(token),
          );
          const matchedSpecificTokens = specificTermTokens.filter((token) =>
            searchTokens.has(token),
          );
          const exactPhraseMatch = this.containsWholeSemanticPhrase(normalizedSearchText, term);
          const specificCoverage =
            matchedSpecificTokens.length / specificTermTokens.length;
          if (
            hiddenAutoDomainRequiresStrongMatch &&
            !(
              (exactPhraseMatch && specificTermTokens.length >= 2) ||
              (matchedSpecificTokens.length >= 2 && specificCoverage >= 0.75)
            )
          ) {
            continue;
          }

          if (exactPhraseMatch) {
            const exactWeight = Math.max(3, specificTermTokens.length * 3);
            score += exactWeight;
            reasons.push(`Matched request phrase: ${term}`);
            continue;
          }

          if (matchedTokens.length === 0) {
            continue;
          }

          if (
            matchedTokens.every((token) => genericTokens.has(token)) ||
            (
              termTokens.length > 1 &&
              matchedTokens.length === 1 &&
              matchedTokens[0] === 'ai'
            )
          ) {
            continue;
          }

          if (termTokens.length > 1 && matchedSpecificTokens.length < 2) {
            continue;
          }

          const coverage =
            matchedSpecificTokens.length / specificTermTokens.length;

          if (
            coverage >= 0.6 ||
            (termTokens.length === 1 && matchedSpecificTokens.length === 1)
          ) {
            const tokenWeight =
              matchedSpecificTokens.length * 2 + (coverage === 1 ? 1 : 0);
            score += tokenWeight;
            reasons.push(
              `Matched request terms: ${matchedSpecificTokens.join(', ')}`,
            );
          }
        }

        return {
          domain,
          score,
          reasons: [...new Set(reasons)].slice(0, 4),
        };
      })
      .sort(
        (first, second) =>
          second.score - first.score ||
          first.domain.name.localeCompare(second.domain.name),
      );

    const bestMatch = rankedDomains[0];

    if (!bestMatch || bestMatch.score < 4) {
      return null;
    }

    const secondBestScore = rankedDomains[1]?.score ?? 0;
    const lead = Math.max(0, bestMatch.score - secondBestScore);

    if (secondBestScore >= 4 && lead < 2 && bestMatch.score < 8) {
      return null;
    }

    const confidence = Math.min(
      0.97,
      0.68 + Math.min(0.2, bestMatch.score * 0.02) + Math.min(0.08, lead * 0.02),
    );

    return {
      domainId: bestMatch.domain.id,
      domainName: bestMatch.domain.name,
      source: DomainResolutionSource.KEYWORD_MATCH,
      confidence,
      trace: {
        reasons: [
          'The current request intent matched this domain more strongly than stored preferences or historical behavior.',
          ...bestMatch.reasons,
        ],
        matchedInterests: [],
        candidates: rankedDomains
          .filter((candidate) => candidate.score > 0)
          .slice(0, 3)
          .map((candidate) => ({
            domainId: candidate.domain.id,
            domainName: candidate.domain.name,
            score: candidate.score,
            reasons:
              candidate.reasons.length > 0
                ? candidate.reasons
                : ['Matched normalized current-request terms'],
          })),
      },
    };
  }

  private containsWholeSemanticPhrase(
    normalizedSearchText: string,
    normalizedTerm: string,
  ): boolean {
    if (!normalizedSearchText || !normalizedTerm) {
      return false;
    }

    return (` ${normalizedSearchText} `).includes(` ${normalizedTerm} `);
  }

  private normalizeSemanticText(value: string): string {
    const aliases: Readonly<Record<string, string>> = {
      financial: 'finance',
      finances: 'finance',
      financing: 'finance',
      administration: 'administrative',
      admin: 'administrative',
      companies: 'business',
      company: 'business',
      businesses: 'business',
      invoicing: 'invoice',
      invoices: 'invoice',
      expenses: 'expense',
      budgeting: 'budget',
      budgets: 'budget',
      reconciliations: 'reconciliation',
      payments: 'payment',
      payrolls: 'payroll',
      procurements: 'procurement',
      employees: 'employee',
      workers: 'worker',
      recruiters: 'recruiter',
      recruiting: 'recruitment',
      hires: 'hiring',
      hired: 'hiring',
      workloads: 'workload',
      costs: 'cost',
      spending: 'expense',
      expenditures: 'expense',
      records: 'record',
      feedbacks: 'feedback',
      breaches: 'breach',
      threats: 'threat',
      attacks: 'attack',
      alerts: 'alert',
      incidents: 'incident',
      credentials: 'credential',
      vulnerabilities: 'vulnerability',
      bands: 'band',
      musicians: 'musician',
      rehearsals: 'rehearsal',
      recordings: 'recording',
      songs: 'song',
      setlists: 'setlist',
      devices: 'device',
    };

    return value
      .trim()
      .toLowerCase()
      .normalize('NFKC')
      .replace(/[^\p{L}\p{N}]+/gu, ' ')
      .split(/\s+/)
      .filter(Boolean)
      .map((token) => aliases[token] ?? token)
      .join(' ');
  }

  private getDomainIntentAliases(domainName: string): readonly string[] {
    const normalizedDomain = this.normalizeComparableValue(domainName);

    if (normalizedDomain === 'finance') {
      return [
        'financial management',
        'financial administration',
        'administrative finance',
        'finance operations',
        'business finance',
        'accounting',
        'bookkeeping',
        'invoice management',
        'expense management',
        'budget management',
        'payroll',
        'procurement',
        'reconciliation',
        'cash flow',
        'back office finance',
      ];
    }

    if (normalizedDomain === 'business operations') {
      return [
        'administration',
        'administrative operations',
        'business operations',
        'company operations',
        'office administration',
        'approval workflow',
        'document workflow',
        'back office operations',
        'internal operations',
        'manual administration',
        'workflow bottleneck',
      ];
    }

    if (
      normalizedDomain === 'tattoo studio operations client management' ||
      normalizedDomain === 'tattoo studio operations & client management' ||
      normalizedDomain === 'tattoo studio management'
    ) {
      return [
        'tattoo studio operations',
        'tattoo artist scheduling',
        'tattoo appointment booking',
        'tattoo booking conflicts',
        'tattoo design revisions',
        'tattoo client feedback',
        'tattoo client preferences',
        'tattoo appointment deposits',
        'tattoo consent forms',
        'tattoo aftercare instructions',
        'tattoo client session history',
        'tattoo studio calendar',
        'tattoo design approval history',
        'tattoo client records',
      ];
    }

    if (
      normalizedDomain === 'shipment traceability chain of custody management' ||
      normalizedDomain === 'shipment traceability & chain of custody management' ||
      normalizedDomain === 'logistics'
    ) {
      return [
        'shipment tracking',
        'high value shipment tracking',
        'shipment chain of custody',
        'shipment handover records',
        'carrier handover tracking',
        'warehouse shipment records',
        'customs checkpoint records',
        'shipment location updates',
        'shipment temperature telemetry',
        'delivery confirmation records',
        'shipment dispute resolution',
        'supply chain partner accountability',
        'shipment event reconciliation',
        'proof of delivery',
      ];
    }

    if (
      normalizedDomain === 'recipe culinary knowledge management' ||
      normalizedDomain === 'recipe & culinary knowledge management' ||
      normalizedDomain === 'personal recipe management'
    ) {
      return [
        'recipe collection',
        'saved recipes',
        'recipe search',
        'ingredient substitutions',
        'recipe modifications',
        'personal recipe changes',
        'cooking results',
        'family recipe preferences',
        'recipe notes',
        'recipe history',
        'cooking notes',
        'recipe version history',
      ];
    }

    if (
      normalizedDomain === 'travel planning comparison' ||
      normalizedDomain === 'travel planning & comparison'
    ) {
      return [
        'travel planning',
        'accommodation comparison',
        'travel price comparison',
        'booking platform comparison',
        'activity availability',
        'transportation options',
        'travel reviews',
        'traveler preferences',
        'trip budget planning',
        'local experiences',
      ];
    }

    if (
      normalizedDomain === 'book club reading group management' ||
      normalizedDomain === 'book club & reading group management' ||
      normalizedDomain === 'reading community coordination'
    ) {
      return [
        'book club',
        'reading group',
        'reading schedule',
        'member reading progress',
        'book club meeting',
        'meeting coordination',
        'discussion topics',
        'discussion history',
        'shared reading notes',
        'book suggestions',
        'reading progress tracking',
        'missed meeting catch up',
      ];
    }

    if (
      normalizedDomain === 'photography studio operations' ||
      normalizedDomain === 'photography workflow management' ||
      normalizedDomain === 'photography studios'
    ) {
      return [
        'photography studio',
        'photo studio',
        'client booking',
        'photo shoot scheduling',
        'shoot schedule',
        'shot list',
        'equipment preparation',
        'camera gear checklist',
        'editing request',
        'image selection',
        'photo selection',
        'gallery selection',
        'client delivery deadline',
        'photo delivery',
        'studio project workflow',
      ];
    }

    if (
      normalizedDomain === 'beauty salon management' ||
      normalizedDomain === 'salon management' ||
      normalizedDomain === 'beauty services' ||
      normalizedDomain === 'personal care services'
    ) {
      return [
        'beauty salon',
        'salon management',
        'salon appointments',
        'appointment scheduling',
        'stylist availability',
        'client preferences',
        'service history',
        'loyalty history',
        'salon inventory',
        'product usage',
        'special requests',
        'double booking',
        'beauty services',
        'personal care services',
      ];
    }

    if (
      normalizedDomain === 'hr recruitment' ||
      normalizedDomain === 'human resources' ||
      normalizedDomain === 'human resources recruitment'
    ) {
      return [
        'human resources',
        'hr',
        'recruitment',
        'hiring',
        'employee',
        'employees',
        'workforce',
        'worker',
        'staff',
        'employee burnout',
        'workplace burnout',
        'employee turnover',
        'staff turnover',
        'retention',
        'candidate screening',
        'applicant tracking',
        'talent acquisition',
        'employee onboarding',
        'employee feedback',
        'hr records',
        'workforce management',
        'workload',
      ];
    }

    if (
      normalizedDomain === 'cybersecurity' ||
      normalizedDomain === 'cyber security' ||
      normalizedDomain === 'information security'
    ) {
      return [
        'cybersecurity',
        'cyber security',
        'information security',
        'security',
        'data security',
        'patient data security',
        'unauthorized access',
        'unauthorised access',
        'access control',
        'data breach',
        'security breach',
        'suspicious activity',
        'security alert',
        'security alerts',
        'threat detection',
        'security monitoring',
        'incident response',
        'cyber attack',
        'cyberattack',
        'malware',
        'ransomware',
        'phishing',
        'vulnerability',
        'credential theft',
        'identity access',
        'authentication security',
        'privacy breach',
        'sensitive data',
      ];
    }

    if (normalizedDomain === 'artificial intelligence') {
      return [
        'artificial intelligence',
        'machine learning',
        'generative ai',
        'ai model',
        'model inference',
        'ai reliability',
        'model hallucination',
        'prompt reliability',
      ];
    }

    if (
      normalizedDomain === 'wardrobe personal fashion management' ||
      normalizedDomain === 'wardrobe fashion management' ||
      normalizedDomain === 'personal wardrobe management' ||
      normalizedDomain === 'digital wardrobe'
    ) {
      return [
        'wardrobe management',
        'digital wardrobe',
        'clothing inventory',
        'clothes inventory',
        'closet organization',
        'shoes and accessories inventory',
        'outfit planning',
        'outfit coordination',
        'clothing fit tracking',
        'clothing cleaning tracking',
        'clothing repair tracking',
        'wardrobe maintenance',
        'shopping receipt wardrobe import',
        'duplicate clothing purchase prevention',
        'seasonal outfit planning',
        'weather based outfit planning',
      ];
    }

    if (
      normalizedDomain === 'tailoring custom apparel' ||
      normalizedDomain === 'tailoring' ||
      normalizedDomain === 'custom apparel'
    ) {
      return [
        'tailoring',
        'tailor shop',
        'custom clothing',
        'custom apparel',
        'customer measurements',
        'body measurements',
        'fabric selection',
        'alteration request',
        'clothing alterations',
        'fitting appointment',
        'design notes',
        'custom order tracking',
        'garment order',
        'made to measure',
        'bespoke clothing',
      ];
    }

    if (
      normalizedDomain === 'pet care management' ||
      normalizedDomain === 'pet care' ||
      normalizedDomain === 'animal care'
    ) {
      return [
        'pet care management',
        'pet health records',
        'vaccination tracking',
        'grooming schedule',
        'feeding routine',
        'pet care coordination',
        'veterinary care history',
        'veterinarian records',
        'pet sitter instructions',
        'shared pet care',
        'pet appointment tracking',
        'animal care records',
      ];
    }

    if (
      normalizedDomain === 'event planning management' ||
      normalizedDomain === 'event planning' ||
      normalizedDomain === 'wedding event management' ||
      normalizedDomain === 'wedding planning'
    ) {
      return [
        'event planning',
        'wedding planning',
        'private event planning',
        'event coordination',
        'wedding coordination',
        'venue coordination',
        'vendor coordination',
        'photographer scheduling',
        'decorator scheduling',
        'catering coordination',
        'guest list management',
        'event budget tracking',
        'event schedule management',
        'last minute event changes',
        'booking conflict prevention',
      ];
    }

    if (
      normalizedDomain === 'funeral memorial services' ||
      normalizedDomain === 'memorial services' ||
      normalizedDomain === 'funeral services'
    ) {
      return [
        'funeral service coordination',
        'memorial service coordination',
        'ceremony scheduling',
        'burial preference tracking',
        'funeral home coordination',
        'guest communication',
        'floral arrangement coordination',
        'family request tracking',
        'memorial transportation coordination',
        'funeral document checklist',
        'bereavement service planning',
      ];
    }

    if (normalizedDomain === 'sports fitness' || normalizedDomain === 'sports and fitness') {
      return [
        'sports training',
        'athlete performance',
        'training load monitoring',
        'overtraining detection',
        'athlete recovery',
        'injury risk monitoring',
        'wearable workout data',
        'fitness equipment telemetry',
        'coach performance dashboard',
      ];
    }

    if (normalizedDomain === 'internet of things' || normalizedDomain === 'iot') {
      return [
        'connected devices',
        'sensor monitoring',
        'device telemetry',
        'device management',
        'edge devices',
        'wearable devices',
        'connected equipment',
        'device protocol compatibility',
      ];
    }

    if (normalizedDomain === 'real estate') {
      return [
        'property data',
        'property records',
        'real estate listings',
        'rental listings',
        'housing search',
        'lease management',
        'property management',
        'real estate data integration',
      ];
    }

    if (normalizedDomain === 'tourism') {
      return [
        'travel planning',
        'travel booking',
        'tourist services',
        'destination management',
        'visitor experience',
        'hotel booking',
      ];
    }

    if (normalizedDomain === 'media entertainment' || normalizedDomain === 'media and entertainment') {
      return [
        'content creation',
        'streaming',
        'audience engagement',
        'media workflow',
        'digital publishing',
        'creator workflow',
        'band rehearsal',
        'music rehearsal',
        'song version management',
        'set list coordination',
        'recording version management',
        'music collaboration',
        'rehearsal scheduling',
      ];
    }

    if (normalizedDomain === 'government' || normalizedDomain === 'public sector') {
      return [
        'government agency',
        'government department',
        'public administration',
        'citizen service',
        'permit application',
        'license processing',
        'official record',
        'public record',
        'approval status',
        'ownership record',
      ];
    }

    if (
      normalizedDomain === 'legaltech' ||
      normalizedDomain === 'legal tech' ||
      normalizedDomain === 'legal technology'
    ) {
      return [
        'legal research',
        'legal document',
        'contract verification',
        'case management',
        'ownership record',
        'record verification',
        'document verification',
        'legal workflow',
        'dispute resolution',
      ];
    }

    if (normalizedDomain === 'blockchain' || normalizedDomain === 'web3') {
      return [
        'blockchain',
        'distributed ledger',
        'smart contract',
        'tamper evident record',
        'record provenance',
        'immutable record',
        'version integrity',
        'audit trail',
      ];
    }

    if (normalizedDomain === 'agriculture') {
      return [
        'agriculture',
        'farming',
        'crop monitoring',
        'crop health',
        'crop disease detection',
        'soil monitoring',
        'soil telemetry',
        'weather forecasting',
        'field prioritization',
        'irrigation scheduling',
        'harvest planning',
        'agricultural resource optimization',
      ];
    }

    if (normalizedDomain === 'e commerce' || normalizedDomain === 'ecommerce') {
      return [
        'online commerce',
        'online store',
        'shopping',
        'checkout',
        'merchant',
        'order management',
      ];
    }

    if (normalizedDomain === 'agriculture') {
      return [
        'farming',
        'farm management',
        'irrigation',
        'crop management',
        'crop monitoring',
        'soil',
        'harvest',
        'agricultural operations',
      ];
    }

    if (normalizedDomain === 'energy') {
      return [
        'electricity',
        'solar',
        'power grid',
        'energy consumption',
        'energy monitoring',
        'battery',
        'utility',
        'power management',
      ];
    }

    if (
      normalizedDomain === 'dance studio operations & performance management'
    ) {
      return [
        'dance studio',
        'class scheduling',
        'instructor availability',
        'student attendance',
        'choreography progress',
        'costume requirements',
        'rehearsal tracking',
        'performance readiness',
      ];
    }

    if (normalizedDomain === 'education') {
      return [
        'learning',
        'teaching',
        'student',
        'students',
        'school',
        'university',
        'homework',
        'assignment',
        'coursework',
        'classroom',
        'grading',
      ];
    }

    if (normalizedDomain === 'healthcare') {
      return ['health', 'medical', 'clinic', 'patient', 'hospital'];
    }

    return [];
  }

  /**
   * Hidden auto-generated domains are narrower than visible catalog domains.
   * A single generic noun is not enough to make one authoritative for a new
   * request. For example, a logistics profitability request can mention
   * "shipment volumes" without being a chain-of-custody problem.
   */
  private isStrongPlannedExistingDomainMatch(
    domain: {
      readonly name: string;
      readonly isVisible: boolean;
      readonly isAutoGenerated: boolean;
    },
    input: ResolveDomainInput,
  ): boolean {
    if (domain.isVisible || !domain.isAutoGenerated) return true;

    const request = this.normalizeSemanticText([
      input.description ?? '',
      ...(input.keywords ?? []),
    ].join(' '));
    if (!request) return true;

    const normalizedDomain = this.normalizeSemanticText(domain.name);

    if (
      normalizedDomain === 'shipment traceability chain of custody management' ||
      normalizedDomain === 'shipment traceability & chain of custody management'
    ) {
      const shipmentIdentity =
        /\b(?:shipment|shipments|cargo|parcel|parcels|carrier|carriers|warehouse|warehouses)\b/u.test(request);
      const custodyWorkflow =
        /\b(?:traceability|chain of custody|custody trail|handover|handoff|proof of delivery|tracking provenance|tamper|customs checkpoint|transfer verification)\b/u.test(request);
      return shipmentIdentity && custodyWorkflow;
    }

    const stopWords = new Set([
      'management', 'operations', 'operation', 'workflow', 'workflows',
      'tracking', 'system', 'systems', 'platform', 'service', 'services',
      'business', 'businesses', 'analytics', 'analysis', 'intelligence',
      'revenue', 'profitability', 'performance', 'forecast', 'forecasting',
      'restoration', 'conservation', 'repair', 'repairs', 'and', 'the',
    ]);
    const identityTokens = normalizedDomain
      .split(/\s+/u)
      .filter((token) => token.length >= 4 && !stopWords.has(token));
    if (identityTokens.length === 0) return true;

    const matched = identityTokens.filter((token) =>
      new RegExp(`(?:^|\\s)${token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?:$|\\s)`, 'u').test(request),
    );
    const required = Math.min(2, identityTokens.length);
    return matched.length >= required;
  }

  private async resolveAuthoritativeNewDomainFast(input: {
    readonly domainName: string;
    readonly keywordCandidates: readonly string[];
    readonly language: LanguageCode;
  }): Promise<{
    readonly id: string;
    readonly name: string;
    readonly isActive: boolean;
    readonly isVisible: boolean;
    readonly isAutoGenerated: boolean;
  } | null> {
    const select = {
      id: true,
      name: true,
      isActive: true,
      isVisible: true,
      isAutoGenerated: true,
    } as const;

    let domain = await this.prisma.domain.findFirst({
      where: { name: { equals: input.domainName, mode: 'insensitive' } },
      select,
    });
    if (domain && !domain.isActive) return null;

    if (!domain) {
      try {
        domain = await this.prisma.domain.create({
          data: {
            name: input.domainName,
            isActive: true,
            isVisible: false,
            isAutoGenerated: true,
          },
          select,
        });
      } catch (error: unknown) {
        if (
          !(
            error instanceof Prisma.PrismaClientKnownRequestError &&
            error.code === 'P2002'
          )
        ) {
          throw error;
        }
        domain = await this.prisma.domain.findFirst({
          where: { name: { equals: input.domainName, mode: 'insensitive' } },
          select,
        });
        if (!domain || !domain.isActive) return null;
      }
    }

    if (
      domain.isAutoGenerated &&
      !domain.isVisible &&
      input.keywordCandidates.length > 0
    ) {
      const domainId = domain.id;
      const keywordCandidates = [...input.keywordCandidates];
      setImmediate(() => {
        void this.prisma.domainKeyword
          .createMany({
            data: keywordCandidates.map((keyword) => ({
              domainId,
              keyword,
              language: input.language,
            })),
            skipDuplicates: true,
          })
          .catch(() => undefined);
      });
    }

    return domain;
  }

  /**
   * Creates a concrete domain when current request text does not match any
   * configured domain. The operation is idempotent and stores a compact search
   * vocabulary so subsequent collection runs can reuse it immediately.
   */
  private async resolveAiPlannedDomain(
    input: ResolveDomainInput,
  ): Promise<DomainResolutionResult | null> {
    if (
      input.plannedDomainSelectionMode === 'EXISTING' &&
      input.plannedExistingDomainId?.trim()
    ) {
      const selected = await this.prisma.domain.findFirst({
        where: {
          id: input.plannedExistingDomainId.trim(),
          isActive: true,
        },
        select: {
          id: true,
          name: true,
          isVisible: true,
          isAutoGenerated: true,
        },
      });

      if (
        selected &&
        !this.isGeneral(selected.name) &&
        this.isStrongPlannedExistingDomainMatch(selected, input)
      ) {
        return {
          domainId: selected.id,
          domainName: selected.name,
          source: DomainResolutionSource.KEYWORD_MATCH,
          confidence: Math.max(
            0.85,
            this.normalizePlannedDomainConfidence(
              input.plannedDomainConfidence,
              0.9,
            ),
          ),
          trace: {
            reasons: [
              'The text-bearing request was classified by AI against the complete active domain catalog, including visible and hidden domains.',
              `The AI selected the existing domain "${selected.name}" by exact catalog id.`,
            ],
            matchedInterests: [],
            candidates: [
              {
                domainId: selected.id,
                domainName: selected.name,
                score: 100,
                reasons: ['Exact AI domain-catalog selection'],
              },
            ],
          },
        };
      }
    }

    if (
      input.plannedDomainSelectionMode === 'NEW' &&
      this.normalizePlannedDomainName(input.plannedDomainName)
    ) {
      return this.resolveOrCreateRequestDomain(input);
    }

    return null;
  }

  private async resolveOrCreateRequestDomain(
    input: ResolveDomainInput,
  ): Promise<DomainResolutionResult | null> {
    if (
      input.plannedDomainSelectionMode === 'EXISTING' &&
      input.plannedExistingDomainId?.trim()
    ) {
      const selected = await this.prisma.domain.findFirst({
        where: {
          id: input.plannedExistingDomainId.trim(),
          isActive: true,
        },
        select: {
          id: true,
          name: true,
          isVisible: true,
          isAutoGenerated: true,
        },
      });
      if (
        selected &&
        !this.isGeneral(selected.name) &&
        !this.isStrongPlannedExistingDomainMatch(selected, input)
      ) {
        return null;
      }

      if (
        selected &&
        !this.isGeneral(selected.name) &&
        this.isStrongPlannedExistingDomainMatch(selected, input)
      ) {
        return {
          domainId: selected.id,
          domainName: selected.name,
          source: DomainResolutionSource.KEYWORD_MATCH,
          confidence: Math.max(
            0.85,
            this.normalizePlannedDomainConfidence(
              input.plannedDomainConfidence,
              0.9,
            ),
          ),
          trace: {
            reasons: [
              'The AI pre-collection classifier selected this exact existing active domain from the complete visible + hidden domain catalog.',
            ],
            matchedInterests: [],
            candidates: [
              {
                domainId: selected.id,
                domainName: selected.name,
                score: 100,
                reasons: ['Exact AI domain-catalog selection'],
              },
            ],
          },
        };
      }
    }

    const requestText = [
      input.description ?? '',
      ...(input.keywords ?? []),
      ...(input.plannedKeywords ?? []),
    ].join(' ');
    const canonicalRequestDomainName = this.inferKnownDomainName(requestText);
    const plannedDomainName = this.normalizePlannedDomainName(
      input.plannedDomainName,
    );
    const domainName =
      input.plannedDomainSelectionMode === 'NEW' && plannedDomainName
        ? plannedDomainName
        : this.chooseRequestDomainName(
            canonicalRequestDomainName,
            plannedDomainName,
            input.plannedDomainConfidence,
          ) ??
          this.inferDomainName(input.description, input.keywords);
    if (!domainName || this.isGeneral(domainName)) {
      return null;
    }

    const keywordCandidates = this.buildAutoDomainKeywords(
      input.description,
      input.keywords,
      domainName,
      input.plannedKeywords,
    );

    /*
     * PREPARING has already shown the AI the complete active domain catalog.
     * When that authoritative plan explicitly says NEW with high confidence,
     * re-running semantic-equivalent hidden-domain discovery inside a remote
     * transaction only repeats work and adds several database round-trips.
     * Resolve an exact-name hit or create the new hidden domain immediately,
     * then persist its keyword metadata asynchronously. A unique-name race is
     * still handled safely by re-reading the winner.
     */
    if (
      input.plannedDomainSelectionMode === 'NEW' &&
      this.normalizePlannedDomainConfidence(input.plannedDomainConfidence) >= 0.7
    ) {
      const fastResolved = await this.resolveAuthoritativeNewDomainFast({
        domainName,
        keywordCandidates,
        language: input.language,
      });
      if (fastResolved) {
        return {
          domainId: fastResolved.id,
          domainName: fastResolved.name,
          source: DomainResolutionSource.KEYWORD_MATCH,
          confidence: Math.max(
            0.72,
            this.normalizePlannedDomainConfidence(
              input.plannedDomainConfidence,
              0.9,
            ),
          ),
          trace: {
            reasons: [
              'The PREPARING AI classified the current request against the active domain catalog and proposed a new narrow professional domain.',
              'The domain identity was resolved on the fast exact-name/create path; keyword metadata persistence is decoupled from the generation critical path.',
            ],
            matchedInterests: [],
            candidates: [
              {
                domainId: fastResolved.id,
                domainName: fastResolved.name,
                score: 1,
                reasons: ['Authoritative PREPARING new-domain resolution'],
              },
            ],
          },
        };
      }
    }

    const persistDomain = () =>
      this.prisma.$transaction(async (transaction) => {
        const existing = await transaction.domain.findFirst({
          where: {
            name: { equals: domainName, mode: 'insensitive' },
          },
          select: {
            id: true,
            name: true,
            isActive: true,
            isVisible: true,
            isAutoGenerated: true,
          },
        });

        if (existing && !existing.isActive) {
          return null;
        }

        const equivalentAutoDomain = existing
          ? null
          : await this.findEquivalentHiddenAutoDomain(transaction, {
              domainName,
              keywordCandidates,
              language: input.language,
            });

        const resolved = existing
          ? existing
          : equivalentAutoDomain
            ? equivalentAutoDomain
            : await transaction.domain.create({
                data: {
                  name: domainName,
                  isActive: true,
                  isVisible: false,
                  isAutoGenerated: true,
                },
                select: {
                  id: true,
                  name: true,
                  isActive: true,
                  isVisible: true,
                  isAutoGenerated: true,
                },
              });

        if (!resolved) {
          return null;
        }

        const canPersistRequestKeywords =
          resolved.isAutoGenerated && !resolved.isVisible;

        if (canPersistRequestKeywords && keywordCandidates.length > 0) {
          await transaction.domainKeyword.createMany({
            data: keywordCandidates.map((keyword) => ({
              domainId: resolved.id,
              keyword,
              language: input.language,
            })),
            skipDuplicates: true,
          });
        }

        return resolved;
      });

    let domain: Awaited<ReturnType<typeof persistDomain>>;
    try {
      domain = await persistDomain();
      if (!domain) {
        return null;
      }
    } catch (error: unknown) {
      /*
       * Two simultaneous unmatched requests can infer the same new domain.
       * Treat the unique-name race as success and reuse the winner instead of
       * surfacing a transient database error to idea generation.
       */
      if (
        !(
          error instanceof Prisma.PrismaClientKnownRequestError &&
          error.code === 'P2002'
        )
      ) {
        throw error;
      }

      const racedDomain = await this.prisma.domain.findFirst({
        where: { name: { equals: domainName, mode: 'insensitive' } },
        select: {
          id: true,
          name: true,
          isActive: true,
          isVisible: true,
          isAutoGenerated: true,
        },
      });
      if (!racedDomain) throw error;
      if (!racedDomain.isActive) return null;

      domain = racedDomain;

      const canPersistRequestKeywords =
        racedDomain.isAutoGenerated && !racedDomain.isVisible;

      if (canPersistRequestKeywords && keywordCandidates.length > 0) {
        await this.prisma.domainKeyword.createMany({
          data: keywordCandidates.map((keyword) => ({
            domainId: racedDomain.id,
            keyword,
            language: input.language,
          })),
          skipDuplicates: true,
        });
      }
    }

    if (!domain) {
      return null;
    }

    return {
      domainId: domain.id,
      domainName: domain.name,
      source: DomainResolutionSource.KEYWORD_MATCH,
      confidence: 0.72,
      trace: {
        reasons: [
          input.plannedDomainName
            ? 'The AI classified the text against every active visible and hidden domain. No existing domain was selected, so the proposed professional domain is reused by exact semantic identity when possible or created as a hidden internal domain before evidence collection.'
            : 'The current request did not match a visible configured domain strongly enough. A semantically equivalent active hidden domain is reused when available; otherwise a new hidden internal domain is created from requester intent instead of falling back to unrelated personalization.',
          domain.isAutoGenerated && !domain.isVisible
            ? `Stored ${keywordCandidates.length} request-derived search keyword(s) on the hidden auto-generated domain for future collection.`
            : 'Kept request-derived search terms inside the current generation context; existing visible-domain keywords were not mutated.',
        ],
        matchedInterests: [],
        candidates: [
          {
            domainId: domain.id,
            domainName: domain.name,
            score: 1,
            reasons: ['Resolved from current-request intent with hidden-domain semantic deduplication'],
          },
        ],
      },
    };
  }

  private async findEquivalentHiddenAutoDomain(
    transaction: Prisma.TransactionClient,
    input: {
      readonly domainName: string;
      readonly keywordCandidates: readonly string[];
      readonly language: LanguageCode;
    },
  ): Promise<{
    readonly id: string;
    readonly name: string;
    readonly isActive: boolean;
    readonly isVisible: boolean;
    readonly isAutoGenerated: boolean;
  } | null> {
    const candidates = await transaction.domain.findMany({
      where: {
        isActive: true,
        isVisible: false,
        isAutoGenerated: true,
      },
      select: {
        id: true,
        name: true,
        isActive: true,
        isVisible: true,
        isAutoGenerated: true,
        domainKeywords: {
          where: {
            language: {
              in: [input.language, LanguageCode.ANY],
            },
          },
          select: {
            keyword: true,
          },
        },
      },
    });

    const requestedNameTokens = this.autoDomainIdentityTokens([
      input.domainName,
    ]);
    const requestedCorpusTokens = this.autoDomainIdentityTokens([
      input.domainName,
      ...input.keywordCandidates,
    ]);
    const requestedWorkflowFamily = this.autoDomainWorkflowFamily([
      input.domainName,
      ...input.keywordCandidates,
    ]);
    const requestedObjectIdentity = new Set(
      RequestQueryProvenanceUtil.extractObjectIdentityTokens([
        input.domainName,
        ...input.keywordCandidates,
      ].join(' ')),
    );

    const ranked = candidates
      .map((candidate) => {
        const candidateNameTokens = this.autoDomainIdentityTokens([
          candidate.name,
        ]);
        const candidateCorpusTokens = this.autoDomainIdentityTokens([
          candidate.name,
          ...candidate.domainKeywords.map((item) => item.keyword),
        ]);
        const candidateWorkflowFamily = this.autoDomainWorkflowFamily([
          candidate.name,
          ...candidate.domainKeywords.map((item) => item.keyword),
        ]);
        const candidateObjectIdentity = new Set(
          RequestQueryProvenanceUtil.extractObjectIdentityTokens([
            candidate.name,
            ...candidate.domainKeywords.map((item) => item.keyword),
          ].join(' ')),
        );
        const objectIdentityOverlap = this.tokenIntersectionSize(
          requestedObjectIdentity,
          candidateObjectIdentity,
        );
        const objectIdentityCompatible =
          requestedObjectIdentity.size === 0 ||
          candidateObjectIdentity.size === 0 ||
          objectIdentityOverlap >= 1;
        const workflowCompatible =
          this.autoDomainWorkflowFamiliesCompatible(
            requestedWorkflowFamily,
            candidateWorkflowFamily,
          );
        const nameOverlap = this.tokenIntersectionSize(
          requestedNameTokens,
          candidateNameTokens,
        );
        const corpusOverlap = this.tokenIntersectionSize(
          requestedCorpusTokens,
          candidateCorpusTokens,
        );
        const smallerCorpusSize = Math.max(
          1,
          Math.min(requestedCorpusTokens.size, candidateCorpusTokens.size),
        );
        const corpusCoverage = corpusOverlap / smallerCorpusSize;
        const score = nameOverlap * 3 + corpusOverlap + corpusCoverage * 4;
        return {
          candidate,
          nameOverlap,
          corpusOverlap,
          corpusCoverage,
          workflowCompatible,
          objectIdentityCompatible,
          objectIdentityOverlap,
          score: score + objectIdentityOverlap * 6,
        };
      })
      .filter(
        (entry) =>
          entry.workflowCompatible &&
          entry.objectIdentityCompatible &&
          /*
           * Hidden-domain reuse must represent the same professional identity,
           * not merely share one craft noun. A one-token overlap such as
           * "embroidery" must not reuse an older customization/engraving
           * domain for an antique-textile restoration workflow.
           */
          (entry.nameOverlap >= 2 ||
            (entry.corpusCoverage >= 0.68 && entry.objectIdentityOverlap >= 2)) &&
          entry.corpusOverlap >= 3 &&
          entry.corpusCoverage >= 0.45,
      )
      .sort(
        (left, right) =>
          right.score - left.score ||
          right.corpusCoverage - left.corpusCoverage ||
          left.candidate.name.localeCompare(right.candidate.name),
      );

    const best = ranked[0]?.candidate;
    if (!best) return null;

    return {
      id: best.id,
      name: best.name,
      isActive: best.isActive,
      isVisible: best.isVisible,
      isAutoGenerated: best.isAutoGenerated,
    };
  }

  private autoDomainWorkflowFamily(
    values: readonly string[],
  ):
    | 'CUSTOM_FOOTWEAR_PRODUCTION'
    | 'SHOE_REPAIR'
    | 'CLOCK_REPAIR'
    | 'FOUNTAIN_PEN_REPAIR'
    | 'VIOLIN_BOW_SERVICE'
    | 'DOLL_RESTORATION'
    | 'UMBRELLA_REPAIR'
    | 'PHOTOGRAPH_RESTORATION'
    | 'WARDROBE_MANAGEMENT'
    | 'CUSTOM_HEADWEAR'
    | 'CUSTOM_WIG'
    | 'TAILORING'
    | 'EYEGLASS_FRAME_REPAIR'
    | 'LEATHER_GOODS_REPAIR'
    | null {
    const text = this.normalizeSemanticText(values.join(' '));

    if (
      /\b(?:fountain pen|fountain pens|pen repair specialist|pen repair specialists|fountain pen repair|fountain pen repairs|nib technician|nib technicians|nibmeister|nibmeisters)\b/u.test(
        text,
      ) &&
      /\b(?:nib adjustment|nib adjustments|ink flow|ink flow problem|ink flow problems|replacement part|replacement parts|previous repair|previous repairs|service history|repair history|writing preference|writing preferences|restoration request|restoration requests|diagnostic|diagnostics)\b/u.test(
        text,
      )
    ) {
      return 'FOUNTAIN_PEN_REPAIR';
    }

    if (RequestNicheCustomCraftUtil.isViolinBowServiceRequest(text)) {
      return 'VIOLIN_BOW_SERVICE';
    }

    const eyeglassRepairActor =
      /\b(?:eyeglass frame repair|eyeglass repair|eyewear repair|optical frame repair|spectacle frame repair|glasses repair)\b/u.test(text);
    const eyeglassRepairWorkflow =
      /\b(?:frame damage|previous repair|repair history|replacement hinge|replacement part|color matching|colour matching|fit preference|customer fit|adjustment note|repeated adjustment|pickup date|promised pickup)\w*\b/u.test(text);
    if (eyeglassRepairActor && eyeglassRepairWorkflow) {
      return 'EYEGLASS_FRAME_REPAIR';
    }

    const leatherGoodsRepairActor =
      /\b(?:leather goods repair|leather bag repair|bag repair specialist|leather repair specialist|handbag repair|leather restoration)\b/u.test(text);
    const leatherGoodsRepairWorkflow =
      /\b(?:leather matching|replacement hardware|zipper|strap|handle|stitching|previous repair|repair history|customer preference|completion date)\w*\b/u.test(text);
    if (leatherGoodsRepairActor && leatherGoodsRepairWorkflow) {
      return 'LEATHER_GOODS_REPAIR';
    }

    const shoeRepairActor =
      /\b(?:shoe repair|shoe repairs|shoe repair shop|shoe repair shops|cobbler|cobblers|cobbler shop|cobbler shops)\b/u.test(
        text,
      );
    const shoeRepairWorkflow =
      /\b(?:repair ticket|paper ticket|requested repair|repair status|technician note|misplaced shoe|pickup date|collection date|repair queue)\b/u.test(
        text,
      );
    if (shoeRepairActor && shoeRepairWorkflow) {
      return 'SHOE_REPAIR';
    }

    const customFootwearActor =
      /\b(?:shoemaker|shoemakers|shoe maker|shoe makers|shoemaking|shoe making|bespoke shoemaker|bespoke shoemakers|custom shoe maker|custom shoe makers|custom footwear|bespoke footwear|handmade shoe|handmade shoes|made to measure shoe|made to measure shoes|cordwainer|cordwainers)\b/u.test(
        text,
      );
    const customFootwearWorkflow =
      /\b(?:foot measurement|foot measurements|leather selection|leather selections|sole type|sole types|stitching preference|stitching preferences|fitting note|fitting notes|design revision|design revisions|approved specification|approved specifications|handmade footwear|custom shoe order)\b/u.test(
        text,
      );
    if (customFootwearActor && customFootwearWorkflow) {
      return 'CUSTOM_FOOTWEAR_PRODUCTION';
    }

    const clockRepairActor =
      /\b(?:clock repair|clock repairs|clock repair specialist|clock repair specialists|clockmaker|clockmakers|horologist|horologists|horology|timepiece repair|antique clock repair)\b/u.test(
        text,
      );
    const clockRepairWorkflow =
      /\b(?:mechanical fault|mechanical faults|replacement part|replacement parts|previous repair|previous repairs|service history|repair history|restoration instruction|restoration instructions|cost approval|cost approvals|completion date|completion dates|promised completion|diagnostic|diagnostics)\b/u.test(
        text,
      );
    if (clockRepairActor && clockRepairWorkflow) {
      return 'CLOCK_REPAIR';
    }

    const umbrellaRepairActor =
      /\b(?:umbrella repair|umbrella repairs|umbrella repair specialist|umbrella repair specialists|umbrella repairer|umbrella repairers|umbrella restoration|parasol repair|parasol repairs)\b/u.test(text);
    const umbrellaRepairWorkflow =
      /\b(?:damaged ribs?|broken ribs?|fabric condition|canopy condition|handle problems?|replacement parts?|previous repairs?|repair history|customer preferences?|pickup dates?|promised pickup|repair notes?|item history)\b/u.test(text);
    if (umbrellaRepairActor && umbrellaRepairWorkflow) {
      return 'UMBRELLA_REPAIR';
    }

    const photographRestorationActor =
      /\b(?:photograph restoration|photo restoration|photograph restoration specialist|photograph restoration specialists|photo restoration specialist|photo restoration specialists|photograph conservator|photograph conservators|photo conservator|photo conservators)\b/u.test(text);
    const photographRestorationWorkflow =
      /\b(?:damaged originals?|scanning details?|requested edits?|retouching|color restoration|colour restoration|revision requests?|restoration notes?|image damage|photo damage|photograph damage)\b/u.test(text);
    if (photographRestorationActor && photographRestorationWorkflow) {
      return 'PHOTOGRAPH_RESTORATION';
    }

    const dollRestorationActor =
      /\b(?:doll restoration|doll restoration specialist|doll restoration specialists|doll restorer|doll restorers|antique doll restoration|doll repair specialist|doll repair specialists)\b/u.test(
        text,
      );
    const dollRestorationWorkflow =
      /\b(?:damage photograph|damage photographs|fabric selection|fabric selections|paint matching|restoration note|restoration notes|doll part|doll parts|replacement part|replacement parts|approved restoration|material sample|material samples)\b/u.test(
        text,
      );
    if (dollRestorationActor && dollRestorationWorkflow) {
      return 'DOLL_RESTORATION';
    }

    if (
      /\b(?:wardrobe|digital wardrobe|closet|outfit planning|outfit planner|personal wardrobe)\b/u.test(
        text,
      ) &&
      /\b(?:inventory|outfit|shopping receipt|duplicate purchase|seasonal|weather|cleaning|wardrobe maintenance)\b/u.test(
        text,
      )
    ) {
      return 'WARDROBE_MANAGEMENT';
    }

    if (
      /\b(?:hat maker|hat makers|milliner|milliners|millinery|custom hat|bespoke hat|custom headwear)\b/u.test(
        text,
      ) &&
      /\b(?:head measurement|head circumference|brim dimension|brim width|decorative detail|fitting note|approved specification)\b/u.test(
        text,
      )
    ) {
      return 'CUSTOM_HEADWEAR';
    }

    if (
      /\b(?:wig maker|wig makers|custom wig|custom wigs|hairpiece maker|hairpiece makers|wig studio|wig artisan)\b/u.test(
        text,
      )
    ) {
      return 'CUSTOM_WIG';
    }

    if (
      /\b(?:tailor|tailors|tailoring|alteration shop|alteration shops|bespoke clothing|custom apparel|garment)\b/u.test(
        text,
      ) &&
      /\b(?:body measurement|garment measurement|fabric selection|alteration request|fitting appointment|custom clothing order)\b/u.test(
        text,
      )
    ) {
      return 'TAILORING';
    }

    return null;
  }

  private autoDomainWorkflowFamiliesCompatible(
    requested:
      | 'CUSTOM_FOOTWEAR_PRODUCTION'
      | 'SHOE_REPAIR'
      | 'CLOCK_REPAIR'
      | 'FOUNTAIN_PEN_REPAIR'
      | 'VIOLIN_BOW_SERVICE'
      | 'DOLL_RESTORATION'
      | 'UMBRELLA_REPAIR'
      | 'PHOTOGRAPH_RESTORATION'
      | 'WARDROBE_MANAGEMENT'
      | 'CUSTOM_HEADWEAR'
      | 'CUSTOM_WIG'
      | 'TAILORING'
      | 'EYEGLASS_FRAME_REPAIR'
      | 'LEATHER_GOODS_REPAIR'
      | null,
    candidate:
      | 'CUSTOM_FOOTWEAR_PRODUCTION'
      | 'SHOE_REPAIR'
      | 'CLOCK_REPAIR'
      | 'FOUNTAIN_PEN_REPAIR'
      | 'VIOLIN_BOW_SERVICE'
      | 'DOLL_RESTORATION'
      | 'UMBRELLA_REPAIR'
      | 'PHOTOGRAPH_RESTORATION'
      | 'WARDROBE_MANAGEMENT'
      | 'CUSTOM_HEADWEAR'
      | 'CUSTOM_WIG'
      | 'TAILORING'
      | 'EYEGLASS_FRAME_REPAIR'
      | 'LEATHER_GOODS_REPAIR'
      | null,
  ): boolean {
    if (requested || candidate) return requested === candidate;
    return true;
  }

  private autoDomainIdentityTokens(values: readonly string[]): Set<string> {
    const stopWords = new Set([
      'management',
      'operations',
      'operation',
      'workflow',
      'workflows',
      'system',
      'systems',
      'platform',
      'platforms',
      'software',
      'application',
      'applications',
      'service',
      'services',
      'business',
      'businesses',
      'independent',
      'professional',
      'professionals',
      'specialist',
      'specialists',
      'technician',
      'technicians',
      'operator',
      'operators',
      'provider',
      'providers',
      'customer',
      'customers',
      'client',
      'clients',
      'tracking',
      'track',
      'documentation',
      'document',
      'documents',
      'treatment',
      'treatments',
      'approval',
      'approvals',
      // Heritage/workflow scaffolding is too generic to prove that two hidden
      // auto-domains describe the same underlying object. Keep the material or
      // object identity (textile, map, jewelry, fountain, violin, etc.) as the
      // part that must overlap before an existing hidden domain can be reused.
      'domain',
      'domains',
      'antique',
      'antiques',
      'historic',
      'historical',
      'vintage',
      'preservation',
      'preserve',
      'preserved',
      'conservation',
      'conserve',
      'conserved',
      'maintenance',
      'equipment',
      'cost',
      'costs',
      'expense',
      'expenses',
      'condition',
      'record',
      'records',
      'repair',
      'repairs',
      'restoration',
      'history',
      'practice',
      'project',
      'projects',
      'shop',
      'shops',
      'workshop',
      'workshops',
      'order',
      'orders',
      'data',
      'digital',
      'analytics',
      'analysis',
      'intelligence',
      'retention',
      'revenue',
      'profitability',
      'performance',
      'forecast',
      'forecasting',
      'prediction',
      'optimization',
      'optimisation',
      'monitoring',
      // Risk/security/workflow vocabulary is intentionally non-identifying for
      // hidden-domain reuse. A marketplace fraud domain must not be considered
      // equivalent to logistics fraud merely because both names contain
      // "security", "fraud", or "detection". Reuse now requires the
      // concrete business/object identity (marketplace, logistics, textile,
      // camera, hospital, etc.) to overlap as well.
      'security',
      'cybersecurity',
      'fraud',
      'fraudulent',
      'detection',
      'detect',
      'risk',
      'risks',
      'identity',
      'access',
      'account',
      'accounts',
      'governance',
      'compliance',
      'investigation',
      'investigations',
      'alert',
      'alerts',
      'anomaly',
      'anomalies',
    ]);

    return new Set(
      values
        .flatMap((value) =>
          this.normalizeSemanticText(value)
            .split(/\s+/u)
            .filter(Boolean),
        )
        .map((token) => this.normalizeAutoDomainIdentityToken(token))
        .filter(
          (token) => token.length >= 4 && !stopWords.has(token),
        ),
    );
  }

  private normalizeAutoDomainIdentityToken(value: string): string {
    let token = value.toLocaleLowerCase();
    if (token.length > 7 && token.endsWith('ing')) {
      token = token.slice(0, -3);
    } else if (token.length > 6 && token.endsWith('ers')) {
      token = token.slice(0, -3);
    } else if (token.length > 5 && token.endsWith('ies')) {
      token = `${token.slice(0, -3)}y`;
    } else if (token.length > 5 && token.endsWith('s')) {
      token = token.slice(0, -1);
    }
    return token;
  }

  private tokenIntersectionSize(
    left: ReadonlySet<string>,
    right: ReadonlySet<string>,
  ): number {
    let count = 0;
    for (const token of left) {
      if (right.has(token)) count += 1;
    }
    return count;
  }

  private normalizePlannedDomainName(value?: string): string | null {
    const normalized = value
      ?.normalize('NFKC')
      .replace(/[-_/]+/gu, ' ')
      .replace(/\s+/gu, ' ')
      .replace(/[.!?]+$/gu, '')
      .trim();

    if (!normalized || normalized.length > 80) return null;
    const words = normalized.split(/\s+/u).filter((word) => word !== '&');
    if (words.length < 2 || words.length > 12) return null;
    if (
      /^(?:people|users|companies|travelers|travellers|members|owners|teams?|students?)\b/iu.test(
        normalized,
      ) ||
      /\b(?:often|struggle|struggles|want to|need to|who|regularly)\b/iu.test(
        normalized,
      )
    ) {
      return null;
    }

    return normalized;
  }

  /** Derives a stable short domain label from unmatched request text. */
  private inferDomainName(
    description?: string,
    keywords?: readonly string[],
  ): string | null {
    const requestText = [description ?? '', ...(keywords ?? [])]
      .join(' ')
      .normalize('NFKC')
      .toLowerCase();
    const knownDomain = this.inferKnownDomainName(requestText);
    if (knownDomain) return knownDomain;

    const stopWords = new Set([
      'a', 'an', 'and', 'are', 'about', 'for', 'from', 'in', 'into', 'is', 'of',
      'on', 'or', 'the', 'to', 'with', 'without', 'problem', 'problems', 'issue',
      'issues', 'need', 'needs', 'want', 'wants', 'software', 'system', 'app',
      'application', 'platform', 'user', 'users', 'using', 'use', 'help', 'make',
      'improve', 'solution', 'solutions', 'often', 'usually', 'frequently',
      'commonly', 'struggle', 'struggles', 'struggling', 'difficult', 'difficulty',
      'keep', 'keeps', 'keeping', 'track', 'tracking', 'several', 'multiple',
      'many', 'different', 'exactly', 'months', 'later', 'when', 'where', 'which',
      'because', 'across', 'among', 'shared', 'responsibility', 'information',
      'حل', 'مشكلة', 'مشاكل', 'في', 'من', 'على', 'عن', 'مع', 'بدون', 'مستخدم',
      'مستخدمين', 'تطبيق', 'نظام',
    ]);

    const source = [
      ...(keywords ?? []),
      description ?? '',
    ]
      .join(' ')
      .normalize('NFKC')
      .toLowerCase()
      .replace(/[^\p{L}\p{N}]+/gu, ' ')
      .split(/\s+/u)
      .filter(Boolean)
      .filter((token) => token.length >= 3 && !stopWords.has(token));

    const unique = [...new Set(source)].slice(0, 3);
    if (unique.length === 0) return null;

    return unique
      .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
      .join(' ')
      .slice(0, 80);
  }

  /**
   * Maps common requester vocabulary to a canonical domain name even when the
   * corresponding domain row does not exist yet. This avoids creating labels
   * such as "Students Homework" when the actual missing domain is Education.
   */
  /**
   * RequestCollectionPlan stores confidence on a 0..1 scale, while older
   * callers historically supplied 0..100. Normalize both contracts here so an
   * AI plan with confidence 0.95 is not accidentally treated as 0.95%.
   */
  private normalizePlannedDomainConfidence(
    value?: number,
    fallback = 0,
  ): number {
    const raw = Number.isFinite(value) ? Number(value) : fallback;
    return Math.max(0, Math.min(1, raw > 1 ? raw / 100 : raw));
  }

  private chooseRequestDomainName(
    canonicalDomainName: string | null,
    plannedDomainName: string | null,
    plannedDomainConfidence?: number,
  ): string | null {
    if (!plannedDomainName) return canonicalDomainName;
    if (!canonicalDomainName) return plannedDomainName;

    const canonical = this.normalizeSemanticText(canonicalDomainName);
    const planned = this.normalizeSemanticText(plannedDomainName);
    if (canonical === planned) return canonicalDomainName;

    const rawConfidence = Number.isFinite(plannedDomainConfidence)
      ? Number(plannedDomainConfidence)
      : 0;
    const normalizedConfidence = Math.max(
      0,
      Math.min(1, rawConfidence > 1 ? rawConfidence / 100 : rawConfidence),
    );
    const plannedIsBroad = new Set([
      'education', 'business operations', 'government', 'logistics', 'healthcare',
      'tourism', 'media entertainment', 'sports fitness', 'artificial intelligence',
      'cybersecurity', 'internet of things', 'food restaurants', 'finance',
      'real estate', 'transportation', 'e commerce', 'agriculture', 'energy',
      'blockchain', 'hr recruitment', 'legaltech', 'pets', 'pet care',
    ]).has(planned);
    if (normalizedConfidence >= 0.85 && !plannedIsBroad) {
      return plannedDomainName;
    }

    const broadCanonicalDomains = new Set([
      'education',
      'business operations',
      'government',
      'logistics',
      'healthcare',
      'tourism',
      'media entertainment',
      'sports fitness',
      'wardrobe personal fashion management',
      'laundry dry cleaning operations',
      'artificial intelligence',
      'cybersecurity',
      'internet of things',
      'food restaurants',
      'finance',
      'real estate',
      'transportation',
      'e commerce',
      'agriculture',
      'energy',
      'blockchain',
      'hr recruitment',
      'legaltech',
    ]);

    return broadCanonicalDomains.has(canonical)
      ? plannedDomainName
      : canonicalDomainName;
  }

  private isStrongCrossDomainRequestMatch(
    domainName: string,
    description?: string,
    keywords?: readonly string[],
  ): boolean {
    const request = this.normalizeSemanticText(
      [description ?? '', ...(keywords ?? [])].join(' '),
    );
    if (!request) return false;

    const domain = this.normalizeSemanticText(domainName);
    if (domain === 'energy') {
      return /\b(?:energy|electricity|power|utility|utilities|grid|solar|battery|fuel|hvac|kwh|kilowatt|meter|smart meter|submeter|gas consumption|electricity consumption|energy consumption)\w*\b/u.test(
        request,
      );
    }

    if (domain === 'cybersecurity') {
      return /\b(?:cybersecurity|security|unauthorized access|account takeover|malicious|attack|breach|fraud|phishing|credential|authentication)\w*\b/u.test(
        request,
      );
    }

    if (domain === 'finance') {
      return /\b(?:finance|financial|costs?|expenses?|revenue|profitability|margin|budget|payment|payments|billing|cash flow|reimbursement|supplier prices?)\w*\b/u.test(
        request,
      );
    }

    return true;
  }

  private inferKnownDomainName(requestText: string): string | null {
    return inferDominantRequestDomainName(requestText);
  }

  /** Builds bounded, search-friendly keywords for an auto-created domain. */
  private buildAutoDomainKeywords(
    description: string | undefined,
    keywords: readonly string[] | undefined,
    domainName: string,
    plannedKeywords?: readonly string[],
  ): string[] {
    const normalized = [
      ...(plannedKeywords ?? []),
      domainName,
      ...this.getDomainIntentAliases(domainName),
      ...(keywords ?? []),
      ...(description ? [description] : []),
    ]
      .map((value) =>
        value
          .normalize('NFKC')
          .toLowerCase()
          .replace(/[^\p{L}\p{N}]+/gu, ' ')
          .replace(/\s+/gu, ' ')
          .trim(),
      )
      .filter(Boolean);

    const genericSearchTokens = new Set([
      'problem', 'problems', 'issue', 'issues', 'need', 'needs', 'software',
      'system', 'application', 'platform', 'often', 'usually', 'frequently',
      'commonly', 'struggle', 'struggles', 'struggling', 'keep', 'keeping',
      'owners', 'owner', 'users', 'user', 'people', 'staff', 'months', 'later',
      'different', 'several', 'multiple', 'exactly', 'because', 'information',
      'difficulty', 'difficult', 'causing', 'cause', 'delayed', 'delay',
      'care', 'management', 'health', 'records', 'tracking', 'planning',
      'transportation', 'budget', 'schedules', 'documents', 'large', 'numbers',
      'still', 'remember', 'what', 'they', 'have', 'their', 'only', 'memory',
      'items', 'pieces', 'specific', 'leading', 'usually', 'kept',
    ]);

    const tokenCandidates = normalized
      .flatMap((value) => value.split(' '))
      .filter((value) => value.length >= 4)
      .filter((value) => !genericSearchTokens.has(value));

    const phraseCandidates = normalized
      .filter((value) => value.split(' ').length <= 6)
      .filter(
        (value) =>
          !value
            .split(' ')
            .every((token) => genericSearchTokens.has(token)),
      )
      .slice(0, 12);

    return [...new Set([...phraseCandidates, ...tokenCandidates])].slice(0, 14);
  }

  /**
   * Selects a deterministic system fallback.
   *
   * The least-used active concrete domain is chosen to avoid permanently
   * favoring the first database row and to improve platform-wide diversity.
   */
  private async resolveSystemFallback(
    domains: readonly DomainCandidate[],
  ): Promise<DomainResolutionResult> {
    const usage = await this.prisma.idea.groupBy({
      by: ['domainId'],
      where: {
        deletedAt: null,
        domainId: {
          in: domains.map((domain) => domain.id),
        },
      },
      _count: {
        _all: true,
      },
    });

    const usageByDomainId = new Map(
      usage.map((item) => [item.domainId, item._count._all]),
    );

    const selectedDomain = [...domains].sort((first, second) => {
      const firstUsage = usageByDomainId.get(first.id) ?? 0;
      const secondUsage = usageByDomainId.get(second.id) ?? 0;

      return firstUsage - secondUsage || first.name.localeCompare(second.name);
    })[0];

    if (!selectedDomain) {
      throw new BadRequestException('No active concrete domain is configured.');
    }

    return {
      domainId: selectedDomain.id,
      domainName: selectedDomain.name,
      source: DomainResolutionSource.SYSTEM_DEFAULT,
      confidence: 0.25,
      trace: {
        reasons: [
          'No explicit request, saved domain preference, or usable user-history signal was available; the deterministic least-used-domain fallback was used.',
        ],
        matchedInterests: [],
        candidates: [
          {
            domainId: selectedDomain.id,
            domainName: selectedDomain.name,
            score: 0.25,
            reasons: ['Deterministic system fallback'],
          },
        ],
      },
    };
  }

  /** Returns true when the request contains meaningful text or keywords. */
  private hasRequestSearchInput(
    description?: string,
    keywords?: readonly string[],
  ): boolean {
    return Boolean(
      description?.trim() || keywords?.some((keyword) => keyword.trim()),
    );
  }

  /** Finds the first active domain matching an ID, name, or normalized key. */
  private findFirstMatchingDomain(
    domains: readonly DomainCandidate[],
    values: readonly string[],
  ): DomainCandidate | null {
    for (const value of values) {
      const normalizedValue = this.normalizeComparableValue(value);

      if (!normalizedValue) {
        continue;
      }

      const matchingDomain = domains.find(
        (domain) =>
          domain.id === value ||
          this.normalizeComparableValue(domain.name) === normalizedValue,
      );

      if (matchingDomain) {
        return matchingDomain;
      }
    }

    return null;
  }

  /** Normalizes catalog keys and domain names for stable comparison. */
  private normalizeComparableValue(value: string): string {
    return value
      .trim()
      .toLowerCase()
      .replace(/[-_&]+/g, ' ')
      .replace(/\s+/g, ' ');
  }

  /**
   * Rejects hidden auto-generated domains whose persisted label is mostly made
   * of generic sentence words. These rows may remain in the database for audit
   * history, but they must never poison future request matching.
   */
  private isSemanticallyUsableHiddenAutoDomain(
    domain: DomainCandidate,
  ): boolean {
    const genericNameTokens = new Set([
      'often',
      'usually',
      'frequently',
      'commonly',
      'struggle',
      'struggles',
      'struggling',
      'keep',
      'keeps',
      'keeping',
      'owner',
      'owners',
      'people',
      'staff',
      'user',
      'users',
      'management',
      'operations',
      'operation',
      'system',
      'platform',
      'software',
      'application',
      'workflow',
      'service',
      'services',
      'data',
      'digital',
      'information',
      'different',
      'multiple',
      'several',
      'difficulty',
      'difficult',
      'tracking',
      'independent',
      'maker',
      'makers',
      'commission',
      'commissions',
      'design',
      'specification',
      'specifications',
      'custom',
      'approval',
    ]);
    const nameTokens = this.normalizeSemanticText(domain.name)
      .split(/\s+/u)
      .filter(Boolean);
    const specificNameTokens = nameTokens.filter(
      (token) => token.length >= 3 && !genericNameTokens.has(token),
    );

    if (specificNameTokens.length < 1) {
      return false;
    }

    return !/\b(?:often|usually|frequently|commonly|struggle|struggles|struggling|keep|keeps|keeping)\b/iu.test(
      domain.name,
    );
  }

  /** Determines whether a domain is a generic non-concrete category. */
  private isGeneral(name: string): boolean {
    const normalizedName = name.trim().toLowerCase();

    return ['general', 'عام', 'all'].includes(normalizedName);
  }

  /** Safely converts a Prisma JSON value into a clean string array. */
  private readStringArray(
    value: Prisma.JsonValue | null | undefined,
  ): string[] {
    if (!Array.isArray(value)) {
      return [];
    }

    return value
      .filter((item): item is string => typeof item === 'string')
      .map((item) => item.trim())
      .filter(Boolean);
  }
}