import {
  IsBoolean,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';

/**
 * DTO for updating an existing project domain.
 *
 * This DTO is used by the Admin module to update
 * one or more properties of an existing software project domain.
 *
 * Endpoint:
 * PATCH /admin/domains/:id
 *
 * All properties are optional, allowing partial updates.
 *
 * Validation rules:
 * - name must be a string.
 * - name must contain between 2 and 100 characters.
 * - isActive must be a boolean when provided.
 *
 * Notes:
 * - Reports and analytics are not handled by this DTO.
 * - Domain statistics and charts are generated by the reporting layer.
 *
 * Example:
 * {
 *   "name": "Education",
 *   "isActive": false
 * }
 *
 * @author Malak
 */
export class UpdateDomainDto {
  /**
   * Updated software project domain name.
   *
   * Example:
   * Education
   */
  @IsOptional()
  @IsString()
  @MinLength(2)
  @MaxLength(100)
  name?: string;

  /**
   * Indicates whether the domain should remain
   * available for users during idea generation.
   *
   * Example:
   * false
   */
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;
}